<!DOCTYPE html>
<html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<title>27 Phân tích sống còn | Cẩm nang dịch tễ học với R</title>
<meta name="author" content="the handbook team">
<!-- JS --><script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.6/clipboard.min.js" integrity="sha256-inc5kl9MA1hkeYUt+EC3BhlIgyp/2jDIyBLS6k3UxPI=" crossorigin="anonymous"></script><script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.2"></script><script src="https://kit.fontawesome.com/6ecbd6c532.js" crossorigin="anonymous"></script><script src="libs/header-attrs-2.6.4/header-attrs.js"></script><script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script><meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<link href="libs/bootstrap-4.6.0/bootstrap.min.css" rel="stylesheet">
<script src="libs/bootstrap-4.6.0/bootstrap.bundle.min.js"></script><script src="libs/bs3compat-0.2.5.1/tabs.js"></script><script src="libs/bs3compat-0.2.5.1/bs3compat.js"></script><link href="libs/bs4_book-1.0.0/bs4_book.css" rel="stylesheet">
<script src="libs/bs4_book-1.0.0/bs4_book.js"></script><script src="libs/htmlwidgets-1.5.3/htmlwidgets.js"></script><link href="libs/datatables-css-0.0.0/datatables-crosstalk.css" rel="stylesheet">
<script src="libs/datatables-binding-0.16/datatables.js"></script><link href="libs/dt-core-1.10.20/css/jquery.dataTables.min.css" rel="stylesheet">
<link href="libs/dt-core-1.10.20/css/jquery.dataTables.extra.css" rel="stylesheet">
<script src="libs/dt-core-1.10.20/js/jquery.dataTables.min.js"></script><link href="libs/nouislider-7.0.10/jquery.nouislider.min.css" rel="stylesheet">
<script src="libs/nouislider-7.0.10/jquery.nouislider.min.js"></script><link href="libs/selectize-0.12.0/selectize.bootstrap3.css" rel="stylesheet">
<script src="libs/selectize-0.12.0/selectize.min.js"></script><link href="libs/crosstalk-1.1.1/css/crosstalk.css" rel="stylesheet">
<script src="libs/crosstalk-1.1.1/js/crosstalk.min.js"></script><script src="libs/kePrint-0.0.1/kePrint.js"></script><link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet">
<link href="libs/tabwid-1.0.0/tabwid.css" rel="stylesheet">
<script src="libs/tabwid-1.0.0/tabwid.js"></script><link href="libs/leaflet-1.3.1/leaflet.css" rel="stylesheet">
<script src="libs/leaflet-1.3.1/leaflet.js"></script><link href="libs/leafletfix-1.0.0/leafletfix.css" rel="stylesheet">
<script src="libs/Proj4Leaflet-1.0.1/proj4-compressed.js"></script><script src="libs/Proj4Leaflet-1.0.1/proj4leaflet.js"></script><link href="libs/rstudio_leaflet-1.3.1/rstudio_leaflet.css" rel="stylesheet">
<script src="libs/leaflet-binding-2.0.3/leaflet.js"></script><script src="libs/leaflet-providers-1.9.0/leaflet-providers_1.9.0.js"></script><script src="libs/leaflet-providers-plugin-2.0.3/leaflet-providers-plugin.js"></script><script src="libs/viz-1.8.2/viz.js"></script><link href="libs/DiagrammeR-styles-0.2/styles.css" rel="stylesheet">
<script src="libs/grViz-binding-1.0.6.1/grViz.js"></script><script src="libs/d3-4.5.0/d3.min.js"></script><script src="libs/sankey-1/sankey.js"></script><script src="libs/sankeyNetwork-binding-0.4/sankeyNetwork.js"></script><script src="libs/plotly-binding-4.9.2.1/plotly.js"></script><script src="libs/typedarray-0.1/typedarray.min.js"></script><link href="libs/plotly-htmlwidgets-css-1.52.2/plotly-htmlwidgets.css" rel="stylesheet">
<script src="libs/plotly-main-1.52.2/plotly-latest.min.js"></script><link href="libs/vis-4.20.1/vis.css" rel="stylesheet">
<script src="libs/vis-4.20.1/vis.min.js"></script><script src="libs/visNetwork-binding-2.0.9/visNetwork.js"></script><link href="libs/font-awesome-4.7.0/css/font-awesome.min.css" rel="stylesheet">
<script src="libs/plotly-basic-1.52.2/plotly-basic-1.52.2.min.js"></script><script src="libs/plotly-cartesian-1.52.2/plotly-cartesian-1.52.2.min.js"></script><script src="libs/proj4js-2.3.15/proj4.js"></script><link href="libs/highcharts-8.1.2/css/motion.css" rel="stylesheet">
<script src="libs/highcharts-8.1.2/highcharts.js"></script><script src="libs/highcharts-8.1.2/highcharts-3d.js"></script><script src="libs/highcharts-8.1.2/highcharts-more.js"></script><script src="libs/highcharts-8.1.2/modules/stock.js"></script><script src="libs/highcharts-8.1.2/modules/map.js"></script><script src="libs/highcharts-8.1.2/modules/annotations.js"></script><script src="libs/highcharts-8.1.2/modules/data.js"></script><script src="libs/highcharts-8.1.2/modules/drilldown.js"></script><script src="libs/highcharts-8.1.2/modules/item-series.js"></script><script src="libs/highcharts-8.1.2/modules/offline-exporting.js"></script><script src="libs/highcharts-8.1.2/modules/overlapping-datalabels.js"></script><script src="libs/highcharts-8.1.2/modules/exporting.js"></script><script src="libs/highcharts-8.1.2/modules/export-data.js"></script><script src="libs/highcharts-8.1.2/modules/funnel.js"></script><script src="libs/highcharts-8.1.2/modules/heatmap.js"></script><script src="libs/highcharts-8.1.2/modules/treemap.js"></script><script src="libs/highcharts-8.1.2/modules/sankey.js"></script><script src="libs/highcharts-8.1.2/modules/dependency-wheel.js"></script><script src="libs/highcharts-8.1.2/modules/organization.js"></script><script src="libs/highcharts-8.1.2/modules/solid-gauge.js"></script><script src="libs/highcharts-8.1.2/modules/streamgraph.js"></script><script src="libs/highcharts-8.1.2/modules/sunburst.js"></script><script src="libs/highcharts-8.1.2/modules/vector.js"></script><script src="libs/highcharts-8.1.2/modules/wordcloud.js"></script><script src="libs/highcharts-8.1.2/modules/xrange.js"></script><script src="libs/highcharts-8.1.2/modules/tilemap.js"></script><script src="libs/highcharts-8.1.2/modules/venn.js"></script><script src="libs/highcharts-8.1.2/modules/gantt.js"></script><script src="libs/highcharts-8.1.2/modules/timeline.js"></script><script src="libs/highcharts-8.1.2/modules/parallel-coordinates.js"></script><script src="libs/highcharts-8.1.2/modules/bullet.js"></script><script src="libs/highcharts-8.1.2/modules/coloraxis.js"></script><script src="libs/highcharts-8.1.2/modules/dumbbell.js"></script><script src="libs/highcharts-8.1.2/modules/lollipop.js"></script><script src="libs/highcharts-8.1.2/modules/series-label.js"></script><script src="libs/highcharts-8.1.2/plugins/motion.js"></script><script src="libs/highcharts-8.1.2/custom/reset.js"></script><script src="libs/highcharts-8.1.2/modules/boost.js"></script><script src="libs/highchart-binding-0.8.2/highchart.js"></script><script src="https://cdn.jsdelivr.net/autocomplete.js/0/autocomplete.jquery.min.js"></script><script src="https://cdn.jsdelivr.net/npm/mark.js@8.11.1/dist/mark.min.js"></script><!-- CSS --><link rel="stylesheet" href="style_bs4.css">
</head>
<body data-spy="scroll" data-target="#toc">

<div class="container-fluid">
<div class="row">
  <header class="col-sm-12 col-lg-3 sidebar sidebar-book"><a class="sr-only sr-only-focusable" href="#content">Skip to main content</a>

    <div class="d-flex align-items-start justify-content-between">
      <h1>
        <a href="index.html" title="">Cẩm nang dịch tễ học với R</a>
      </h1>
      <button class="btn btn-outline-primary d-lg-none ml-2 mt-1" type="button" data-toggle="collapse" data-target="#main-nav" aria-expanded="true" aria-controls="main-nav"><i class="fas fa-bars"></i><span class="sr-only">Show table of contents</span></button>
    </div>

    <div id="main-nav" class="collapse-lg">
      <form role="search">
        <input id="search" class="form-control" type="search" placeholder="Search" aria-label="Search">
</form>

      <nav aria-label="Table of contents"><h2>Table of contents</h2>
        <ul class="book-toc list-unstyled">
<li><a class="" href="index.html"></a></li>
<li class="book-part">Về cuốn sách này</li>
<li><a class="" href="editorial-style.html"><span class="header-section-number">1</span> Biên tập và ghi chú kỹ thuật</a></li>
<li><a class="" href="data-used.html"><span class="header-section-number">2</span> Tải sách và dữ liệu</a></li>
<li class="book-part">Nhập môn về R</li>
<li><a class="" href="basics.html"><span class="header-section-number">3</span> R Cơ bản</a></li>
<li><a class="" href="transition-to-R.html"><span class="header-section-number">4</span> Chuyển đổi sang R</a></li>
<li><a class="" href="packages-suggested.html"><span class="header-section-number">5</span> Package đề xuất</a></li>
<li><a class="" href="r-projects.html"><span class="header-section-number">6</span> Dự án R</a></li>
<li><a class="" href="importing.html"><span class="header-section-number">7</span> Nhập xuất dữ liệu</a></li>
<li class="book-part">Quản lý dữ liệu</li>
<li><a class="" href="cleaning.html"><span class="header-section-number">8</span> Làm sạch số liệu và các hàm quan trọng</a></li>
<li><a class="" href="dates.html"><span class="header-section-number">9</span> Làm việc với ngày tháng</a></li>
<li><a class="" href="characters-strings.html"><span class="header-section-number">10</span> Ký tự và chuỗi</a></li>
<li><a class="" href="factors.html"><span class="header-section-number">11</span> Factors</a></li>
<li><a class="" href="pivoting.html"><span class="header-section-number">12</span> Xoay trục dữ liệu</a></li>
<li><a class="" href="grouping.html"><span class="header-section-number">13</span> Nhóm dữ liệu</a></li>
<li><a class="" href="joining-matching.html"><span class="header-section-number">14</span> Nối dữ liệu</a></li>
<li><a class="" href="deduplication.html"><span class="header-section-number">15</span> Loại bỏ trùng lặp</a></li>
<li><a class="" href="iteration.html"><span class="header-section-number">16</span> Lặp, vòng lặp, và danh sách</a></li>
<li class="book-part">Phân tích dữ liệu</li>
<li><a class="" href="tables-descriptive.html"><span class="header-section-number">17</span> Bảng mô tả</a></li>
<li><a class="" href="stat-tests.html"><span class="header-section-number">18</span> Các kiểm định thống kê cơ bản</a></li>
<li><a class="" href="regression.html"><span class="header-section-number">19</span> Hồi quy đơn và đa biến</a></li>
<li><a class="" href="missing-data.html"><span class="header-section-number">20</span> Dữ liệu Missing</a></li>
<li><a class="" href="standardization.html"><span class="header-section-number">21</span> Tỷ suất chuẩn hóa</a></li>
<li><a class="" href="moving-average.html"><span class="header-section-number">22</span> Đường trung bình động</a></li>
<li><a class="" href="time-series.html"><span class="header-section-number">23</span> Chuỗi thời gian và phát hiện ổ dịch</a></li>
<li><a class="" href="epidemic-models.html"><span class="header-section-number">24</span> Mô hình hóa dịch bệnh</a></li>
<li><a class="" href="contact-tracing.html"><span class="header-section-number">25</span> Truy vết tiếp xúc</a></li>
<li><a class="" href="survey-analysis.html"><span class="header-section-number">26</span> Phân tích khảo sát</a></li>
<li><a class="active" href="survival-analysis.html"><span class="header-section-number">27</span> Phân tích sống còn</a></li>
<li><a class="" href="gis.html"><span class="header-section-number">28</span> GIS cơ bản</a></li>
<li class="book-part">Trực quan hóa dữ liệu</li>
<li><a class="" href="tables-presentation.html"><span class="header-section-number">29</span> Trình bày bảng</a></li>
<li><a class="" href="ggplot-basics.html"><span class="header-section-number">30</span> ggplot cơ bản</a></li>
<li><a class="" href="ggplot-tips.html"><span class="header-section-number">31</span> Các tips với ggplot</a></li>
<li><a class="" href="epicurves.html"><span class="header-section-number">32</span> Đường cong dịch bệnh</a></li>
<li><a class="" href="age-pyramid.html"><span class="header-section-number">33</span> Tháp dân số và thang đo Likert</a></li>
<li><a class="" href="heatmaps.html"><span class="header-section-number">34</span> Biểu đồ nhiệt</a></li>
<li><a class="" href="diagrams.html"><span class="header-section-number">35</span> Sơ đồ và biểu đồ</a></li>
<li><a class="" href="combination-analysis.html"><span class="header-section-number">36</span> Biểu đồ kết hợp</a></li>
<li><a class="" href="transmission-chains.html"><span class="header-section-number">37</span> Chuỗi lây nhiễm</a></li>
<li><a class="" href="phylogenetic-trees.html"><span class="header-section-number">38</span> Cây phả hệ</a></li>
<li><a class="" href="interactive-plots.html"><span class="header-section-number">39</span> Biểu đồ tương tác</a></li>
<li class="book-part">Báo cáo và dashboards</li>
<li><a class="" href="rmarkdown.html"><span class="header-section-number">40</span> Báo cáo với R Markdown</a></li>
<li><a class="" href="reportfactory.html"><span class="header-section-number">41</span> Tổ chức báo cáo định kỳ</a></li>
<li><a class="" href="flexdashboard.html"><span class="header-section-number">42</span> Dashboards với R Markdown</a></li>
<li><a class="" href="shiny-basics.html"><span class="header-section-number">43</span> Dashboards với Shiny</a></li>
<li class="book-part">Tổng hợp</li>
<li><a class="" href="writing-functions.html"><span class="header-section-number">44</span> Viết hàm</a></li>
<li><a class="" href="directories.html"><span class="header-section-number">45</span> Tương tác với thư mục làm việc</a></li>
<li><a class="" href="collaboration.html"><span class="header-section-number">46</span> Version control với Git và Github</a></li>
<li><a class="" href="errors.html"><span class="header-section-number">47</span> Các lỗi thường gặp</a></li>
<li><a class="" href="help.html"><span class="header-section-number">48</span> Nhờ sự trợ giúp</a></li>
<li><a class="" href="network-drives.html"><span class="header-section-number">49</span> R trên ổ cứng mạng</a></li>
<li><a class="" href="data-table.html"><span class="header-section-number">50</span> Data Table</a></li>
</ul>

        <div class="book-extra">
          
        </div>
      </nav>
</div>
  </header><main class="col-sm-12 col-md-9 col-lg-7" id="content"><div id="survival-analysis" class="section level1" number="27">
<h1>
<span class="header-section-number">27</span> Phân tích sống còn<a class="anchor" aria-label="anchor" href="#survival-analysis"><i class="fas fa-link"></i></a>
</h1>
<div class="inline-figure"><img src="images/survival_analysis.png" width="75%" style="display: block; margin: auto;"></div>
<!-- ======================================================= -->
<div id="tổng-quan-5" class="section level2" number="27.1">
<h2>
<span class="header-section-number">27.1</span> Tổng quan<a class="anchor" aria-label="anchor" href="#t%E1%BB%95ng-quan-5"><i class="fas fa-link"></i></a>
</h2>
<p><em>Phân tích sống còn</em> tập trung mô tả cho một cá thể hay một nhóm cá thể nhất định. Một điểm xác định của một sự kiện được gọi là <strong><em>failure</em></strong> (như là xuất hiện bệnh, chữa khỏi bệnh, tử vong, tái phát sau khi đáp ứng với điều trị…) mà xảy ra sau một khoảng thời gian được gọi là <strong><em>failure time (thời gian dẫn đến sự kiện)</em></strong> (hoặc <strong><em>follow-up time (thời gian theo dõi)</em></strong> trong nghiên cứu thuần tập/nghiên cứu dựa vào dân số) trong suốt thời gian các cá thể được quan sát. Để xác định thời gian dẫn đến sự kiện, chúng ta cần xác định thời điểm bắt đầu (có thể là ngày nhận vào, ngày chẩn đoán…).</p>
<p>Mục tiêu suy luận đối với phân tích sống còn là khoảng thời gian giữa thời điểm bắt đầu và thời điểm sự kiện xảy ra.
Trong nghiên cứu y học hiện nay, phân tích sống còn được sử dụng rộng rãi trong các nghiên cứu lâm sàng để đánh giá hiệu quả của một phương phương điều trị hoặc để đánh giá tình trạng sống còn của một số các biện pháp điều trị ung thư.</p>
<p>Nó thường được diễn đạt qua <strong><em>survival probability (xác suất sống sót)</em></strong> là xác suất mà sự hiện đang quan tâm không xảy ra trong khoảng thời gian t.</p>
<p><strong><em>Censoring</em></strong>: Censoring xảy ra khi sự kiện đang quan tâm không xảy ra trong một số cá thể ở cuối quá trình theo dõi, và vì thế, thời gian thật dẫn đến sự kiện của những cá thể này là không biết. Trong chương này, chúng tôi tập trung chủ yếu vào sự kiện không xảy ra về phía bên phải. Để biết thêm chi tiết về các loại censoring và phân tích sống còn nói chung, xem thêm các tài liệu tham khảo.</p>
<!-- ======================================================= -->
</div>
<div id="chuẩn-bị-17" class="section level2" number="27.2">
<h2>
<span class="header-section-number">27.2</span> Chuẩn bị<a class="anchor" aria-label="anchor" href="#chu%E1%BA%A9n-b%E1%BB%8B-17"><i class="fas fa-link"></i></a>
</h2>
<div id="gọi-packages-7" class="section level3 unnumbered">
<h3>Gọi packages<a class="anchor" aria-label="anchor" href="#g%E1%BB%8Di-packages-7"><i class="fas fa-link"></i></a>
</h3>
<p><strong>Survival</strong> là gói lệnh được sử dụng rộng rãi nhất để phân tích sống còn bằng R. Đầu tiên, chúng ta cài đặt và sau đó tải gói lệnh này cũng như các gói lệnh khác sẽ được sử dụng trong phần này:</p>
<p>Trong cuốn sổ tay này, chúng tôi nhấn mạnh đến hàm <code><a href="https://rdrr.io/pkg/pacman/man/p_load.html">p_load()</a></code> từ package <strong>pacman</strong>, giúp cài đặt package nếu cần thiết <em>và</em> gọi chúng ra để sử dụng. Bạn cũng có thể gọi các package đã được cài đặt bằng hàm <code><a href="https://rdrr.io/r/base/library.html">library()</a></code> trong <strong>base</strong> R. Xem chương <a href="basics.html#basics">R cơ bản</a> để biết thêm thông tin về các package trong R.</p>
<p>Chương này sẽ tìm hiểu phân tích sống còn bằng cách dùng bộ số liệu linelist đã được sử dụng trong hầu hết các chương trước và thay đổi một vài điểm để tạo ra bộ số liệu phù hợp cho phân tích sống còn.</p>
</div>
<div id="nhập-bộ-số-liệu" class="section level3 unnumbered">
<h3>Nhập bộ số liệu<a class="anchor" aria-label="anchor" href="#nh%E1%BA%ADp-b%E1%BB%99-s%E1%BB%91-li%E1%BB%87u"><i class="fas fa-link"></i></a>
</h3>
<p>Chúng ta nhập bộ số liệu của các ca bệnh được mô phỏng từ một vụ dịch Ebola. Để tiện làm theo, <a href="https://github.com/appliedepi/epirhandbook_eng/raw/master/data/case_linelists/linelist_cleaned.rds" class="download-button">bấm để tải số liệu linelist “đã được làm sạch”</a> (dưới dạng tệp .rds). Nhập số liệu này bằng hàm <code><a href="https://rdrr.io/pkg/rio/man/import.html">import()</a></code> từ package <strong>rio</strong> (hàm này chấp nhận nhiều loại tập tin như .xlsx, .rds, .csv – xem chi tiết trong chương [Nhập xuất số liệu].</p>
<div class="sourceCode" id="cb1270"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># import linelist</span>
<span class="va">linelist_case_data</span> <span class="op">&lt;-</span> <span class="fu">rio</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/rio/man/import.html">import</a></span><span class="op">(</span><span class="st">"linelist_cleaned.rds"</span><span class="op">)</span></code></pre></div>
</div>
<div id="quản-lý-và-chuyển-đổi-số-liệu" class="section level3 unnumbered">
<h3>Quản lý và chuyển đổi số liệu<a class="anchor" aria-label="anchor" href="#qu%E1%BA%A3n-l%C3%BD-v%C3%A0-chuy%E1%BB%83n-%C4%91%E1%BB%95i-s%E1%BB%91-li%E1%BB%87u"><i class="fas fa-link"></i></a>
</h3>
<p>Nói ngắn gọn, số liệu cho phân tích sống còn có ba đặc điểm sau:</p>
<ol style="list-style-type: decimal">
<li>biến phụ thuộc hay đáp ứng là khoảng thời gian từ thời điểm bắt đầu đến thời điểm một sự kiện (được xác định rõ) xảy ra,</li>
<li>quan sát censored là các quan sát mà sự kiện quan tâm không xảy ra tại thời điểm phân tích số liệu, và</li>
<li>các biến dự đoán hay giải thích có ảnh hưởng đến thời gian dẫn đến sự kiện mà chúng ta muốn đánh giá hoặc kiểm soát.</li>
</ol>
<p>Do đó, chúng ta sẽ tạo các biến số khác nhau tuân theo cấu trúc dữ liệu đó và tiến hành phân tích sống còn.</p>
<p>Chúng ta định nghĩa:</p>
<ul>
<li>một bộ số liệu mới <code>linelist_surv</code> cho phân tích này<br>
</li>
<li>sự kiện quan tâm là “tử vong” (vì thế xác suất sống sót sẽ là xác suất sống trong một khoảng thời gian nhất định sau thời đểm bắt đầu),</li>
<li>thời gian theo dõi (<code>futime</code>) là <em>số ngày</em> giữa thời điểm khởi phát bệnh và thời điểm có kết cục,</li>
<li>bệnh nhân censored là những người đã hồi phục hoặc những người không biết kết cục, ví dụ như sự kiện “tử vong” không được quan sát (<code>event=0</code>).</li>
</ul>
<p><span style="color: orange;"><strong><em>THẬN TRỌNG:</em></strong> Trong một nghiên cứu thuần tập thực tế, thông tin về thời điểm bắt đầu và thời điểm kết thúc theo dõi của các cá thể là được biết, do đó chúng ta sẽ loại bỏ các quan sát không có ngày bắt đầu và ngày có kết cục. Ngoài ra, các trường hợp có ngày khởi phát bệnh trễ hơn ngày có kết cục cũng bị loại bỏ vì các trường hợp này được xem là sai.</span></p>
<p><span style="color: darkgreen;"><strong><em>MẸO:</em></strong> Khi lọc đến các giá trị lớn hơn (&gt;) hoặc nhỏ hơn (&lt;) một ngày có thể loại bỏ các hàng có giá trị missing, nên khi áp dụng lọc sai ngày cũng sẽ loại bỏ các hàng có ngày bị thiếu.</span></p>
<p>Sau đó, chúng ta sử dụng hàm <code>case_when()</code> để tạo ra một cột <code>age_cat_small</code> mà chỉ có 3 giá trị của nhóm tuổi.</p>
<div class="sourceCode" id="cb1271"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co">#create a new data called linelist_surv from the linelist_case_data</span>

<span class="va">linelist_surv</span> <span class="op">&lt;-</span>  <span class="va">linelist_case_data</span> <span class="op">%&gt;%</span> 
     
  <span class="fu">dplyr</span><span class="fu">::</span><span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span>
       <span class="co"># remove observations with wrong or missing dates of onset or date of outcome</span>
       <span class="va">date_outcome</span> <span class="op">&gt;</span> <span class="va">date_onset</span><span class="op">)</span> <span class="op">%&gt;%</span> 
  
  <span class="fu">dplyr</span><span class="fu">::</span><span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span>
       <span class="co"># create the event var which is 1 if the patient died and 0 if he was right censored</span>
       event <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/ifelse.html">ifelse</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/NA.html">is.na</a></span><span class="op">(</span><span class="va">outcome</span><span class="op">)</span> <span class="op">|</span> <span class="va">outcome</span> <span class="op">==</span> <span class="st">"Recover"</span>, <span class="fl">0</span>, <span class="fl">1</span><span class="op">)</span>, 
    
       <span class="co"># create the var on the follow-up time in days</span>
       futime <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/double.html">as.double</a></span><span class="op">(</span><span class="va">date_outcome</span> <span class="op">-</span> <span class="va">date_onset</span><span class="op">)</span>, 
    
       <span class="co"># create a new age category variable with only 3 strata levels</span>
       age_cat_small <span class="op">=</span> <span class="fu">dplyr</span><span class="fu">::</span><span class="fu"><a href="https://dplyr.tidyverse.org/reference/case_when.html">case_when</a></span><span class="op">(</span> 
            <span class="va">age_years</span> <span class="op">&lt;</span> <span class="fl">5</span>  <span class="op">~</span> <span class="st">"0-4"</span>,
            <span class="va">age_years</span> <span class="op">&gt;=</span> <span class="fl">5</span> <span class="op">&amp;</span> <span class="va">age_years</span> <span class="op">&lt;</span> <span class="fl">20</span> <span class="op">~</span> <span class="st">"5-19"</span>,
            <span class="va">age_years</span> <span class="op">&gt;=</span> <span class="fl">20</span>   <span class="op">~</span> <span class="st">"20+"</span><span class="op">)</span>,
       
       <span class="co"># previous step created age_cat_small var as character.</span>
       <span class="co"># now convert it to factor and specify the levels.</span>
       <span class="co"># Note that the NA values remain NA's and are not put in a level "unknown" for example,</span>
       <span class="co"># since in the next analyses they have to be removed.</span>
       age_cat_small <span class="op">=</span> <span class="fu">fct_relevel</span><span class="op">(</span><span class="va">age_cat_small</span>, <span class="st">"0-4"</span>, <span class="st">"5-19"</span>, <span class="st">"20+"</span><span class="op">)</span>
       <span class="op">)</span></code></pre></div>
<p><span style="color: darkgreen;"><strong><em>MẸO:</em></strong> Chúng ta có thể kiểm tra lại các cột mới đã được tạo ra bằng cách thực hiện tóm tắt đối với biến số <code>futime</code> avà bảng chéo giữa biến số <code>event</code> và biến kết cục <code>outcome</code>. Bên cạnh việc kiểm tra này, đây là một thói quen tốt để biết được thời gian theo dõi trung vị khi giải thích kết quả của phân tích sống còn.</span></p>
<div class="sourceCode" id="cb1272"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">linelist_surv</span><span class="op">$</span><span class="va">futime</span><span class="op">)</span></code></pre></div>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##    1.00    6.00   10.00   11.98   16.00   64.00</code></pre>
<div class="sourceCode" id="cb1274"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># cross tabulate the new event var and the outcome var from which it was created</span>
<span class="co"># to make sure the code did what it was intended to</span>
<span class="va">linelist_surv</span> <span class="op">%&gt;%</span> 
  <span class="fu">tabyl</span><span class="op">(</span><span class="va">outcome</span>, <span class="va">event</span><span class="op">)</span></code></pre></div>
<pre><code>##  outcome    0    1
##    Death    0 1952
##  Recover 1547    0
##     &lt;NA&gt; 1040    0</code></pre>
<p>Bây giờ, chúng ta tạo bảng chéo giữa biến nhóm tuổi mới <code>age_cat_small</code> và biến nhóm tuổi cũ <code>age_cat</code> để đảm bảo tính chính xác của việc chuyển đổi số liệu</p>
<div class="sourceCode" id="cb1276"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">linelist_surv</span> <span class="op">%&gt;%</span> 
  <span class="fu">tabyl</span><span class="op">(</span><span class="va">age_cat_small</span>, <span class="va">age_cat</span><span class="op">)</span></code></pre></div>
<pre><code>##  age_cat_small 0-4 5-9 10-14 15-19 20-29 30-49 50-69 70+ NA_
##            0-4 834   0     0     0     0     0     0   0   0
##           5-19   0 852   717   575     0     0     0   0   0
##            20+   0   0     0     0   862   554    69   5   0
##           &lt;NA&gt;   0   0     0     0     0     0     0   0  71</code></pre>
<p>Bây giờ, chúng ta xem lại 10 quan sát đầu tiên của bộ số liệu <code>linelist_surv</code> bằng cách xem xét các biến cụ thể (bao gồm cả các biến mới được tạo ra).</p>
<div class="sourceCode" id="cb1278"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">linelist_surv</span> <span class="op">%&gt;%</span> 
  <span class="fu">select</span><span class="op">(</span><span class="va">case_id</span>, <span class="va">age_cat_small</span>, <span class="va">date_onset</span>, <span class="va">date_outcome</span>, <span class="va">outcome</span>, <span class="va">event</span>, <span class="va">futime</span><span class="op">)</span> <span class="op">%&gt;%</span> 
  <span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="fl">10</span><span class="op">)</span></code></pre></div>
<pre><code>##    case_id age_cat_small date_onset date_outcome outcome event futime
## 1   8689b7           0-4 2014-05-13   2014-05-18 Recover     0      5
## 2   11f8ea           20+ 2014-05-16   2014-05-30 Recover     0     14
## 3   893f25           0-4 2014-05-21   2014-05-29 Recover     0      8
## 4   be99c8          5-19 2014-05-22   2014-05-24 Recover     0      2
## 5   07e3e8          5-19 2014-05-27   2014-06-01 Recover     0      5
## 6   369449           0-4 2014-06-02   2014-06-07   Death     1      5
## 7   f393b4           20+ 2014-06-05   2014-06-18 Recover     0     13
## 8   1389ca           20+ 2014-06-05   2014-06-09   Death     1      4
## 9   2978ac          5-19 2014-06-06   2014-06-15   Death     1      9
## 10  fc15ef          5-19 2014-06-16   2014-07-09 Recover     0     23</code></pre>
<p>Chúng ta cũng có thể tạo bảng chéo giữa cột biến <code>age_cat_small</code> và <code>gender</code> để biết thêm chi tiết về sự phân bố của biến số mới này theo giới tính. Chúng ta sử dụng hàm <code>tabyl()</code> và hàm <em>adorn</em> từ package <strong>janitor</strong> như được mô tả trong chương <a href="tables-descriptive.html#tables-descriptive">Bảng mô tả</a>.</p>
<!-- For this we use the `stat.table()` function of the **Epi** package. -->
<div class="sourceCode" id="cb1280"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">linelist_surv</span> <span class="op">%&gt;%</span> 
  <span class="fu">tabyl</span><span class="op">(</span><span class="va">gender</span>, <span class="va">age_cat_small</span>, show_na <span class="op">=</span> <span class="cn">F</span><span class="op">)</span> <span class="op">%&gt;%</span> 
  <span class="fu">adorn_totals</span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"row"</span>, <span class="st">"col"</span><span class="op">)</span><span class="op">)</span> <span class="op">%&gt;%</span> 
  <span class="fu">adorn_percentages</span><span class="op">(</span><span class="op">)</span> <span class="op">%&gt;%</span> 
  <span class="fu">adorn_pct_formatting</span><span class="op">(</span><span class="op">)</span> <span class="op">%&gt;%</span> 
  <span class="fu">adorn_ns</span><span class="op">(</span>position <span class="op">=</span> <span class="st">"front"</span><span class="op">)</span></code></pre></div>
<pre><code>##  gender         0-4         5-19          20+         Total
##       f 482 (22.4%) 1184 (54.9%)  490 (22.7%) 2156 (100.0%)
##       m 325 (15.0%)  880 (40.6%)  960 (44.3%) 2165 (100.0%)
##   Total 807 (18.7%) 2064 (47.8%) 1450 (33.6%) 4321 (100.0%)</code></pre>
<!-- Epi::stat.table(  -->
<!--   #give variables for the cross tabulation -->
<!--   list( -->
<!--     gender,  -->
<!--     age_cat_small -->
<!--     ), -->
<!--   #precise the function you want to call (mean,count..) -->
<!--   list(  -->
<!--     count(), -->
<!--     percent(age_cat_small) -->
<!--     ),  -->
<!--   #add margins -->
<!--   margins=T,  -->
<!--   #data used -->
<!--   data = linelist_surv  -->
<!--   ) -->
<!-- ``` -->
<!-- ======================================================= -->
</div>
</div>
<div id="cơ-bản-về-phân-tích-sống-còn" class="section level2" number="27.3">
<h2>
<span class="header-section-number">27.3</span> Cơ bản về phân tích sống còn<a class="anchor" aria-label="anchor" href="#c%C6%A1-b%E1%BA%A3n-v%E1%BB%81-ph%C3%A2n-t%C3%ADch-s%E1%BB%91ng-c%C3%B2n"><i class="fas fa-link"></i></a>
</h2>
<div id="tạo-ra-đối-tượng-kiểu-surv" class="section level3 unnumbered">
<h3>Tạo ra đối tượng kiểu surv<a class="anchor" aria-label="anchor" href="#t%E1%BA%A1o-ra-%C4%91%E1%BB%91i-t%C6%B0%E1%BB%A3ng-ki%E1%BB%83u-surv"><i class="fas fa-link"></i></a>
</h3>
<p>Đầu tiên, chúng ta dùng hàm <code>Surv()</code> từ package <strong>survival</strong> để tạo ra một ‘đối tượng surv’ từ cột follow-up time và event.</p>
<p>Kết quả của bước này tạo ra một đối tượng <em>Surv</em> bao gồm thông tin thời gian và có hay không sự kiện quan tâm (tử vong) được nhận thấy. Đối tượng này sẽ được sử dụng sau này ở phía bên phải trong công thức của những mô hình tiếp theo (xem <a href="https://cran.r-project.org/web/packages/survival/vignettes/survival.pdf">tài liệu</a>).</p>
<div class="sourceCode" id="cb1282"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># Use Suv() syntax for right-censored data</span>
<span class="va">survobj</span> <span class="op">&lt;-</span> <span class="fu">Surv</span><span class="op">(</span>time <span class="op">=</span> <span class="va">linelist_surv</span><span class="op">$</span><span class="va">futime</span>,
                event <span class="op">=</span> <span class="va">linelist_surv</span><span class="op">$</span><span class="va">event</span><span class="op">)</span></code></pre></div>
<!-- ```{r} -->
<!-- survobj <- with(linelist_surv, -->
<!--                 survival::Surv(futime, event) -->
<!--                 ) -->
<!-- ``` -->
<p>Để xem lại số liệu, đây là 10 hàng đầu tiên của bộ số liệu <code>linelist_surv</code> data, chỉ hiển thị các cột quan trọng.</p>
<div class="sourceCode" id="cb1283"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">linelist_surv</span> <span class="op">%&gt;%</span> 
  <span class="fu">select</span><span class="op">(</span><span class="va">case_id</span>, <span class="va">date_onset</span>, <span class="va">date_outcome</span>, <span class="va">futime</span>, <span class="va">outcome</span>, <span class="va">event</span><span class="op">)</span> <span class="op">%&gt;%</span> 
  <span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="fl">10</span><span class="op">)</span></code></pre></div>
<pre><code>##    case_id date_onset date_outcome futime outcome event
## 1   8689b7 2014-05-13   2014-05-18      5 Recover     0
## 2   11f8ea 2014-05-16   2014-05-30     14 Recover     0
## 3   893f25 2014-05-21   2014-05-29      8 Recover     0
## 4   be99c8 2014-05-22   2014-05-24      2 Recover     0
## 5   07e3e8 2014-05-27   2014-06-01      5 Recover     0
## 6   369449 2014-06-02   2014-06-07      5   Death     1
## 7   f393b4 2014-06-05   2014-06-18     13 Recover     0
## 8   1389ca 2014-06-05   2014-06-09      4   Death     1
## 9   2978ac 2014-06-06   2014-06-15      9   Death     1
## 10  fc15ef 2014-06-16   2014-07-09     23 Recover     0</code></pre>
<p>Và đây là 10 thành phần đầu tiên của đối tượng <code>survobj</code>. Về bản chất, nó xuất ra đưới dạng một véc tơ của biến số thời gian theo dõi, dấu “+” là đại điện cho một quan sát censored ở phía bên phải. Xem cách các con số sắp xếp bên trên và bên dưới.</p>
<div class="sourceCode" id="cb1285"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co">#print the 50 first elements of the vector to see how it presents</span>
<span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="va">survobj</span>, <span class="fl">10</span><span class="op">)</span></code></pre></div>
<pre><code>##  [1]  5+ 14+  8+  2+  5+  5  13+  4   9  23+</code></pre>
</div>
<div id="thực-hiện-các-phân-tích-ban-đầu" class="section level3 unnumbered">
<h3>Thực hiện các phân tích ban đầu<a class="anchor" aria-label="anchor" href="#th%E1%BB%B1c-hi%E1%BB%87n-c%C3%A1c-ph%C3%A2n-t%C3%ADch-ban-%C4%91%E1%BA%A7u"><i class="fas fa-link"></i></a>
</h3>
<p>Sau đó, chúng ta bắt đầu phân tích bằng cách sử dụng hàm <code>survfit()</code> để tạo ra một <em>đối tượng survfit</em>, phù hợp với các tính toán mặc định cho các ước tính <strong><em>Kaplan Meier</em></strong> (KM) của đường cong sống sót chung (cận biên), mà thực tế là một hàm bước với các bước nhảy tại thời điểm sự kiện được quan sát. Đối tượng <em>survfit object</em> cuối cùng chứa đựng một hoặc nhiều đường cong sống sót và được tạo ra bằng cách sử dụng đối tượng <em>Surv</em> làm biến đáp ứng trong công thức của mô hình.</p>
<p><span style="color: black;"><strong><em>LƯU Ý:</em></strong> Ước tính Kaplan-Meier là một ước tính khả dĩ tối đa phi tham số của hàm sống còn (xem mục Tài nguyên học liệu để biết thêm thông tin).</span></p>
<p>Tóm tắt của <em>đối tượng survfit</em> này sẽ cho một bảng được gọi là <em>life table (bảng sống còn)</em>. Đối với mỗi bước thời gian theo dõi (<code>time</code>) là nơi một sự kiện xảy ra (theo thứ tự tăng dần):</p>
<ul>
<li>số người có nguy cơ dẫn đến sự kiện (người chưa có sự kiện cũng như sự kiện chưa xảy ra: <code>n.risk</code>)<br>
</li>
<li>những người có sự kiện (<code>n.event</code>)<br>
</li>
<li>và từ những dữ kiện trên tính xác suất không đưa đến sự kiện (xác suất không tử vong, hoặc sống sót sau khoảng thời gian cụ thể đó)<br>
</li>
<li>cuối cùng, sai số chuẩn và khoảng tin cậy cho xác suất đó được tính toán và trình bày</li>
</ul>
<p>Chúng ta thực hiện các ước tính KM bằng cách sử dụng công thức với đối tượng Surv trước đó “survobj” làm biến đáp ứng. “~ 1” diễn đạt rẳng chúng ta đang thực hiện mô hình sống còn tổng quát.</p>
<div class="sourceCode" id="cb1287"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># fit the KM estimates using a formula where the Surv object "survobj" is the response variable.</span>
<span class="co"># "~ 1" signifies that we run the model for the overall survival  </span>
<span class="va">linelistsurv_fit</span> <span class="op">&lt;-</span>  <span class="fu">survival</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/survival/man/survfit.html">survfit</a></span><span class="op">(</span><span class="va">survobj</span> <span class="op">~</span> <span class="fl">1</span><span class="op">)</span>

<span class="co">#print its summary for more details</span>
<span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">linelistsurv_fit</span><span class="op">)</span></code></pre></div>
<pre><code>## Call: survfit(formula = survobj ~ 1)
## 
##  time n.risk n.event survival std.err lower 95% CI upper 95% CI
##     1   4539      30    0.993 0.00120        0.991        0.996
##     2   4500      69    0.978 0.00217        0.974        0.982
##     3   4394     149    0.945 0.00340        0.938        0.952
##     4   4176     194    0.901 0.00447        0.892        0.910
##     5   3899     214    0.852 0.00535        0.841        0.862
##     6   3592     210    0.802 0.00604        0.790        0.814
##     7   3223     179    0.757 0.00656        0.745        0.770
##     8   2899     167    0.714 0.00700        0.700        0.728
##     9   2593     145    0.674 0.00735        0.660        0.688
##    10   2311     109    0.642 0.00761        0.627        0.657
##    11   2081     119    0.605 0.00788        0.590        0.621
##    12   1843      89    0.576 0.00809        0.560        0.592
##    13   1608      55    0.556 0.00823        0.540        0.573
##    14   1448      43    0.540 0.00837        0.524        0.556
##    15   1296      31    0.527 0.00848        0.511        0.544
##    16   1152      48    0.505 0.00870        0.488        0.522
##    17   1002      29    0.490 0.00886        0.473        0.508
##    18    898      21    0.479 0.00900        0.462        0.497
##    19    798       7    0.475 0.00906        0.457        0.493
##    20    705       4    0.472 0.00911        0.454        0.490
##    21    626      13    0.462 0.00932        0.444        0.481
##    22    546       8    0.455 0.00948        0.437        0.474
##    23    481       5    0.451 0.00962        0.432        0.470
##    24    436       4    0.447 0.00975        0.428        0.466
##    25    378       4    0.442 0.00993        0.423        0.462
##    26    336       3    0.438 0.01010        0.419        0.458
##    27    297       1    0.436 0.01017        0.417        0.457
##    29    235       1    0.435 0.01030        0.415        0.455
##    38     73       1    0.429 0.01175        0.406        0.452</code></pre>
<p>Khi sử dụng hàm <code><a href="https://rdrr.io/r/base/summary.html">summary()</a></code>, chúng ta có thể thêm tùy chọn <code>times</code> và cụ thể các thời điểm nhất định mà chúng ta muốn xem các thông tin sống còn</p>
<div class="sourceCode" id="cb1289"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co">#print its summary at specific times</span>
<span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">linelistsurv_fit</span>, times <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">5</span>,<span class="fl">10</span>,<span class="fl">20</span>,<span class="fl">30</span>,<span class="fl">60</span><span class="op">)</span><span class="op">)</span></code></pre></div>
<pre><code>## Call: survfit(formula = survobj ~ 1)
## 
##  time n.risk n.event survival std.err lower 95% CI upper 95% CI
##     5   3899     656    0.852 0.00535        0.841        0.862
##    10   2311     810    0.642 0.00761        0.627        0.657
##    20    705     446    0.472 0.00911        0.454        0.490
##    30    210      39    0.435 0.01030        0.415        0.455
##    60      2       1    0.429 0.01175        0.406        0.452</code></pre>
<p>Chúng ta cũng có thể sử dụng hàm <code><a href="https://rdrr.io/r/base/print.html">print()</a></code>. Đối số <code>print.rmean = TRUE</code> được sử dụng để có được giá trị trung bình của thời gian sống sót và sai số chuẩn (se).</p>
<p><span style="color: black;"><strong><em>LƯU Ý:</em></strong> Thời gian sống sót trung bình giới hạn là một đo lường sống còn cụ thể ngày càng được sử dụng trong phân tích sống còn của bệnh ung thư và thường được định nghĩa là khu vực dưới đường cong, khi chúng ta quan sát bệnh nhân cho đến thời gian giới hạn T (xem phần Tài nguyên học liệu để biết thêm chi tiết).</span></p>
<div class="sourceCode" id="cb1291"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># print linelistsurv_fit object with mean survival time and its se. </span>
<span class="fu"><a href="https://rdrr.io/r/base/print.html">print</a></span><span class="op">(</span><span class="va">linelistsurv_fit</span>, print.rmean <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></code></pre></div>
<pre><code>## Call: survfit(formula = survobj ~ 1)
## 
##          n     events     *rmean *se(rmean)     median    0.95LCL    0.95UCL 
##   4539.000   1952.000     33.105      0.539     17.000     16.000     18.000 
##     * restricted mean with upper limit =  64</code></pre>
<p><span style="color: darkgreen;"><strong><em>MẸO:</em></strong> Chúng ta có thể tạo ra <em>đối tượng surv</em> trực tiếp trong hàm <code>survfit()</code> và tiết kiệm một dòng lệnh. Thực hiện điều này như sau: <code>linelistsurv_quick &lt;-  survfit(Surv(futime, event) ~ 1, data=linelist_surv)</code>.</span></p>
</div>
<div id="mối-nguy-tích-lũy" class="section level3 unnumbered">
<h3>Mối nguy tích lũy<a class="anchor" aria-label="anchor" href="#m%E1%BB%91i-nguy-t%C3%ADch-l%C5%A9y"><i class="fas fa-link"></i></a>
</h3>
<p>Bên cạnh hàm <code><a href="https://rdrr.io/r/base/summary.html">summary()</a></code>, chúng ta có thể sử dụng hàm <code><a href="https://rdrr.io/r/utils/str.html">str()</a></code>, hàm này cho biết chi tiết hơn vể cấu trúc của các đối tượng trong hàm <code>survfit()</code>. Cấu trúc này là một danh sách của 16 thành phần.</p>
<p>Một thành phần quan trọng trong số những thành phần này là: <code>cumhaz</code>, một véc tơ kiểu số. Thành phần này có thể được vẽ để hiển thị <strong><em>mối nguy tích lũy</em></strong>, với <strong><em>mối nguy</em></strong> là <strong><em>tỷ suất xảy ra sự kiện tức thời</em></strong> (xem tài liệu tham khảo).</p>
<div class="sourceCode" id="cb1293"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/utils/str.html">str</a></span><span class="op">(</span><span class="va">linelistsurv_fit</span><span class="op">)</span></code></pre></div>
<pre><code>## List of 16
##  $ n        : int 4539
##  $ time     : num [1:59] 1 2 3 4 5 6 7 8 9 10 ...
##  $ n.risk   : num [1:59] 4539 4500 4394 4176 3899 ...
##  $ n.event  : num [1:59] 30 69 149 194 214 210 179 167 145 109 ...
##  $ n.censor : num [1:59] 9 37 69 83 93 159 145 139 137 121 ...
##  $ surv     : num [1:59] 0.993 0.978 0.945 0.901 0.852 ...
##  $ std.err  : num [1:59] 0.00121 0.00222 0.00359 0.00496 0.00628 ...
##  $ cumhaz   : num [1:59] 0.00661 0.02194 0.05585 0.10231 0.15719 ...
##  $ std.chaz : num [1:59] 0.00121 0.00221 0.00355 0.00487 0.00615 ...
##  $ type     : chr "right"
##  $ logse    : logi TRUE
##  $ conf.int : num 0.95
##  $ conf.type: chr "log"
##  $ lower    : num [1:59] 0.991 0.974 0.938 0.892 0.841 ...
##  $ upper    : num [1:59] 0.996 0.982 0.952 0.91 0.862 ...
##  $ call     : language survfit(formula = survobj ~ 1)
##  - attr(*, "class")= chr "survfit"</code></pre>
<!-- ======================================================= -->
</div>
<div id="vẽ-đường-cong-kaplan-meir" class="section level3 unnumbered">
<h3>Vẽ đường cong Kaplan-Meir<a class="anchor" aria-label="anchor" href="#v%E1%BA%BD-%C4%91%C6%B0%E1%BB%9Dng-cong-kaplan-meir"><i class="fas fa-link"></i></a>
</h3>
<p>Sau khi ước tính KM đã được fit, chúng ta có thể hình dung xác suất sống sót qua một thời gian nhất định bằng cách dùng hàm <code><a href="https://rdrr.io/r/graphics/plot.default.html">plot()</a></code> để vẽ “đường cong Kaplan-Meier”. Nói cách khác, đường cong bên dưới là một minh họa đường cong sống sót quy ước của toàn bộ nhóm bệnh nhân.</p>
<p>Chúng ta có thể nhanh chóng xác minh thời gian theo dõi tối thiểu và tối đa trên đường cong.</p>
<p>Một cách dễ dàng để giải thích là phát biểu rằng, tại thời điểm 0, tất cả người tham gia đều sống và xác suất sống sót khi đó là 100%.Xác suất ngày giảm dần theo thời gian khi có bệnh nhân tử vong. Tỷ lệ người tham gia sống sót sau 60 ngày là khoảng 40%.</p>
<div class="sourceCode" id="cb1295"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html">plot</a></span><span class="op">(</span><span class="va">linelistsurv_fit</span>, 
     xlab <span class="op">=</span> <span class="st">"Days of follow-up"</span>,    <span class="co"># x-axis label</span>
     ylab<span class="op">=</span><span class="st">"Survival Probability"</span>,   <span class="co"># y-axis label</span>
     main<span class="op">=</span> <span class="st">"Overall survival curve"</span> <span class="co"># figure title</span>
     <span class="op">)</span></code></pre></div>
<div class="inline-figure"><img src="_main_files/figure-html/unnamed-chunk-917-1.png" width="672"></div>
<p>Khoảng tin cậy của các ước tính KM cũng được vẽ mặc định trên biểu đồ và có thể bị loại bỏ bằng cách thêm tùy chọn <code>conf.int = FALSE</code> vào trong lệnh <code><a href="https://rdrr.io/r/graphics/plot.default.html">plot()</a></code>.</p>
<p>Vì sự kiện quan tâm là “tử vong”, việc vẽ một đường cong mô tả phần bù tỷ lệ sống sót sẽ đưa đến việc vẽ tỷ lệ tử vong tích lũy. Điều này có thể được thực hiện với hàm <code><a href="https://rdrr.io/r/graphics/lines.html">lines()</a></code>, bổ sung thông tin trên biểu đồ hiện có.</p>
<div class="sourceCode" id="cb1296"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># original plot</span>
<span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html">plot</a></span><span class="op">(</span>
  <span class="va">linelistsurv_fit</span>,
  xlab <span class="op">=</span> <span class="st">"Days of follow-up"</span>,       
  ylab <span class="op">=</span> <span class="st">"Survival Probability"</span>,       
  mark.time <span class="op">=</span> <span class="cn">TRUE</span>,              <span class="co"># mark events on the curve: a "+" is printed at every event</span>
  conf.int <span class="op">=</span> <span class="cn">FALSE</span>,              <span class="co"># do not plot the confidence interval</span>
  main <span class="op">=</span> <span class="st">"Overall survival curve and cumulative mortality"</span>
  <span class="op">)</span>

<span class="co"># draw an additional curve to the previous plot</span>
<span class="fu"><a href="https://rdrr.io/r/graphics/lines.html">lines</a></span><span class="op">(</span>
  <span class="va">linelistsurv_fit</span>,
  lty <span class="op">=</span> <span class="fl">3</span>,             <span class="co"># use different line type for clarity</span>
  fun <span class="op">=</span> <span class="st">"event"</span>,       <span class="co"># draw the cumulative events instead of the survival </span>
  mark.time <span class="op">=</span> <span class="cn">FALSE</span>,
  conf.int <span class="op">=</span> <span class="cn">FALSE</span>
  <span class="op">)</span>

<span class="co"># add a legend to the plot</span>
<span class="fu"><a href="https://rdrr.io/r/graphics/legend.html">legend</a></span><span class="op">(</span>
  <span class="st">"topright"</span>,                               <span class="co"># position of legend</span>
  legend <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"Survival"</span>, <span class="st">"Cum. Mortality"</span><span class="op">)</span>, <span class="co"># legend text </span>
  lty <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">1</span>, <span class="fl">3</span><span class="op">)</span>,                            <span class="co"># line types to use in the legend</span>
  cex <span class="op">=</span> <span class="fl">.85</span>,                                <span class="co"># parametes that defines size of legend text</span>
  bty <span class="op">=</span> <span class="st">"n"</span>                                 <span class="co"># no box type to be drawn for the legend</span>
  <span class="op">)</span></code></pre></div>
<div class="inline-figure"><img src="_main_files/figure-html/unnamed-chunk-918-1.png" width="672"></div>
<!-- ======================================================= -->
</div>
</div>
<div id="so-sánh-các-đường-cong-sống-sót" class="section level2" number="27.4">
<h2>
<span class="header-section-number">27.4</span> So sánh các đường cong sống sót<a class="anchor" aria-label="anchor" href="#so-s%C3%A1nh-c%C3%A1c-%C4%91%C6%B0%E1%BB%9Dng-cong-s%E1%BB%91ng-s%C3%B3t"><i class="fas fa-link"></i></a>
</h2>
<p>Để so sánh các đường cong sống sót của những nhóm người tham gia hoặc bệnh nhân khác nhau, đầu tiên chúng ta có thể cần xem xét các đường cong tương ứng của các nhóm và sau đó thực hiện các kiểm định để lượng giá sự khác biệt giữa các nhóm độc lập. So sánh này có thể liên quan đến các nhóm dựa vào giới tính, tuổi tác, điều trị, bệnh đi kèm,…</p>
<div id="kiểm-định-log-rank" class="section level3 unnumbered">
<h3>Kiểm định Log rank<a class="anchor" aria-label="anchor" href="#ki%E1%BB%83m-%C4%91%E1%BB%8Bnh-log-rank"><i class="fas fa-link"></i></a>
</h3>
<p>Kiểm định log rank là một kiểm định phổ biến để so sánh toàn bộ quá trình sống sót giữa hai hay nhiều nhóm <em>độc lập</em> và có thể xem xét các đường cong sống sót có tương đồng (chồng chéo) hay không (giả thuyết vô hiệu là không có sự khác biệt về sự sống sót giữa các nhóm). Hàm <code>survdiff()</code> trong <strong>survival package</strong> cho phép thực hiện kiểm định log-rank khi chúng ta cụ thể <code>rho = 0</code> (mặc định). Kết quả kiểm định cho ra một thống kê chi bình phương cùng với giá trị p vì log-rank phân phối gần giống như thống kê của kiểm định chi bình phương.</p>
<p>Đầu tiên, chúng ta thử so sánh các đường cong sống sót theo giới tính. Đối với điều này, chúng ta thử hình dung nó (kiểm tra xem hai đường cong sống sót có chồng lên nhau không). Một <em>đối tượng survfit</em> mới sẽ được tạo ra với một công thức hơi khác một chút. Sau đó, <em>đối tượng survdiff</em> sẽ được tạo ra.</p>
<p>Bằng cách cung cấp <code>~ gender</code> ở phía bên phải của công thức, chúng ta không còn vẽ biểu đồ đường cong sống sót chung mà thay vào đó là theo giới tính.</p>
<div class="sourceCode" id="cb1297"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># create the new survfit object based on gender</span>
<span class="va">linelistsurv_fit_sex</span> <span class="op">&lt;-</span>  <span class="fu">survfit</span><span class="op">(</span><span class="fu">Surv</span><span class="op">(</span><span class="va">futime</span>, <span class="va">event</span><span class="op">)</span> <span class="op">~</span> <span class="va">gender</span>, data <span class="op">=</span> <span class="va">linelist_surv</span><span class="op">)</span></code></pre></div>
<p>Bây giờ, chúng ta có thể vẽ các đường cong sống sót theo giới tính. Hãy xem <em>thứ tự</em> giá trị biến của giới tính trước khi xác định màu sắc và chú giải.</p>
<div class="sourceCode" id="cb1298"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># set colors</span>
<span class="va">col_sex</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"lightgreen"</span>, <span class="st">"darkgreen"</span><span class="op">)</span>

<span class="co"># create plot</span>
<span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html">plot</a></span><span class="op">(</span>
  <span class="va">linelistsurv_fit_sex</span>,
  col <span class="op">=</span> <span class="va">col_sex</span>,
  xlab <span class="op">=</span> <span class="st">"Days of follow-up"</span>,
  ylab <span class="op">=</span> <span class="st">"Survival Probability"</span><span class="op">)</span>

<span class="co"># add legend</span>
<span class="fu"><a href="https://rdrr.io/r/graphics/legend.html">legend</a></span><span class="op">(</span>
  <span class="st">"topright"</span>,
  legend <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"Female"</span>,<span class="st">"Male"</span><span class="op">)</span>,
  col <span class="op">=</span> <span class="va">col_sex</span>,
  lty <span class="op">=</span> <span class="fl">1</span>,
  cex <span class="op">=</span> <span class="fl">.9</span>,
  bty <span class="op">=</span> <span class="st">"n"</span><span class="op">)</span></code></pre></div>
<div class="inline-figure"><img src="_main_files/figure-html/unnamed-chunk-919-1.png" width="672"></div>
<p>Và bây giờ, chúng ta có thể tính toán kiểm định sự khác biệt giữa các đường cong bằng cách sử dụng hàm <code>survdiff()</code></p>
<div class="sourceCode" id="cb1299"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co">#compute the test of the difference between the survival curves</span>
<span class="fu">survival</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/survival/man/survdiff.html">survdiff</a></span><span class="op">(</span>
  <span class="fu">Surv</span><span class="op">(</span><span class="va">futime</span>, <span class="va">event</span><span class="op">)</span> <span class="op">~</span> <span class="va">gender</span>, 
  data <span class="op">=</span> <span class="va">linelist_surv</span>
  <span class="op">)</span></code></pre></div>
<pre><code>## Call:
## survival::survdiff(formula = Surv(futime, event) ~ gender, data = linelist_surv)
## 
## n=4321, 218 observations deleted due to missingness.
## 
##             N Observed Expected (O-E)^2/E (O-E)^2/V
## gender=f 2156      924      909     0.255     0.524
## gender=m 2165      929      944     0.245     0.524
## 
##  Chisq= 0.5  on 1 degrees of freedom, p= 0.5</code></pre>
<p>Chúng ta thấy rằng đường cong sống sót cho nữ và đường cong cho nam chồng lên nhau và kiểm định log-rank không đưa ra bằng chứng về sự khác biệt sống sót giữa nam và nữ.</p>
<p>Một số package trong R cho phép minh họa các đường cong sống sót cho các nhóm và kiểm định sự khác biệt cùng một lúc. Sử dụng hàm <code>ggsurvplot()</code> từ package <strong>survminer</strong>, chúng ta cũng có thể bao gồm các bảng nguy cơ với các đường cong này cũng như giá trị p từ kiểm định log-rank.</p>
<p><span style="color: orange;"><strong><em>THẬN TRỌNG:</em></strong> Các hàm từ package <strong>survminer</strong> đòi hỏi chúng ta cụ thể đối tượng sống sót <em>và</em> cụ thể bộ số liệu để so sánh đối tượng sống sót. Hãy nhớ làm điều này để tránh thông báo lỗi do không cụ thể. </span></p>
<div class="sourceCode" id="cb1301"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu">survminer</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/survminer/man/ggsurvplot.html">ggsurvplot</a></span><span class="op">(</span>
    <span class="va">linelistsurv_fit_sex</span>, 
    data <span class="op">=</span> <span class="va">linelist_surv</span>,          <span class="co"># again specify the data used to fit linelistsurv_fit_sex </span>
    conf.int <span class="op">=</span> <span class="cn">FALSE</span>,              <span class="co"># do not show confidence interval of KM estimates</span>
    surv.scale <span class="op">=</span> <span class="st">"percent"</span>,        <span class="co"># present probabilities in the y axis in %</span>
    break.time.by <span class="op">=</span> <span class="fl">10</span>,            <span class="co"># present the time axis with an increment of 10 days</span>
    xlab <span class="op">=</span> <span class="st">"Follow-up days"</span>,
    ylab <span class="op">=</span> <span class="st">"Survival Probability"</span>,
    pval <span class="op">=</span> <span class="cn">T</span>,                      <span class="co"># print p-value of Log-rank test </span>
    pval.coord <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">40</span>,<span class="fl">.91</span><span class="op">)</span>,        <span class="co"># print p-value at these plot coordinates</span>
    risk.table <span class="op">=</span> <span class="cn">T</span>,                <span class="co"># print the risk table at bottom </span>
    legend.title <span class="op">=</span> <span class="st">"Gender"</span>,       <span class="co"># legend characteristics</span>
    legend.labs <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"Female"</span>,<span class="st">"Male"</span><span class="op">)</span>,
    font.legend <span class="op">=</span> <span class="fl">10</span>, 
    palette <span class="op">=</span> <span class="st">"Dark2"</span>,             <span class="co"># specify color palette </span>
    surv.median.line <span class="op">=</span> <span class="st">"hv"</span>,       <span class="co"># draw horizontal and vertical lines to the median survivals</span>
    ggtheme <span class="op">=</span> <span class="fu">theme_light</span><span class="op">(</span><span class="op">)</span>        <span class="co"># simplify plot background</span>
<span class="op">)</span></code></pre></div>
<div class="inline-figure"><img src="_main_files/figure-html/unnamed-chunk-921-1.png" width="672"></div>
<p>Chúng ta có thể cũng muốn kiểm định sự khác biệt về sống còn theo nguồn lây (nguồn ô nhiễm).</p>
<p>Trong trường hợp này, kiểm định log-rank cho thấy có đủ bằng chứng về sự khác biệt trong xác suất sống sót với <code>alpha= 0.005</code>. Xác suất sống sót cho những bệnh nhân bị nhiễm tại các đám tang cao hơn xác suất sống sót ở những nơi khác mà gợi ý về lợi ích sống sót.</p>
<div class="sourceCode" id="cb1302"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">linelistsurv_fit_source</span> <span class="op">&lt;-</span>  <span class="fu">survfit</span><span class="op">(</span>
  <span class="fu">Surv</span><span class="op">(</span><span class="va">futime</span>, <span class="va">event</span><span class="op">)</span> <span class="op">~</span> <span class="va">source</span>,
  data <span class="op">=</span> <span class="va">linelist_surv</span>
  <span class="op">)</span>

<span class="co"># plot</span>
<span class="fu">ggsurvplot</span><span class="op">(</span> 
  <span class="va">linelistsurv_fit_source</span>,
  data <span class="op">=</span> <span class="va">linelist_surv</span>,
  size <span class="op">=</span> <span class="fl">1</span>, linetype <span class="op">=</span> <span class="st">"strata"</span>,   <span class="co"># line types</span>
  conf.int <span class="op">=</span> <span class="cn">T</span>,
  surv.scale <span class="op">=</span> <span class="st">"percent"</span>,  
  break.time.by <span class="op">=</span> <span class="fl">10</span>, 
  xlab <span class="op">=</span> <span class="st">"Follow-up days"</span>,
  ylab<span class="op">=</span> <span class="st">"Survival Probability"</span>,
  pval <span class="op">=</span> <span class="cn">T</span>,
  pval.coord <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">40</span>,<span class="fl">.91</span><span class="op">)</span>,
  risk.table <span class="op">=</span> <span class="cn">T</span>,
  legend.title <span class="op">=</span> <span class="st">"Source of \ninfection"</span>,
  legend.labs <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"Funeral"</span>, <span class="st">"Other"</span><span class="op">)</span>,
  font.legend <span class="op">=</span> <span class="fl">10</span>,
  palette <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"#E7B800"</span>,<span class="st">"#3E606F"</span><span class="op">)</span>,
  surv.median.line <span class="op">=</span> <span class="st">"hv"</span>, 
  ggtheme <span class="op">=</span> <span class="fu">theme_light</span><span class="op">(</span><span class="op">)</span>
<span class="op">)</span></code></pre></div>
<pre><code>## Warning: Vectorized input to `element_text()` is not officially supported.
## Results may be unexpected or may change in future versions of ggplot2.</code></pre>
<div class="inline-figure"><img src="_main_files/figure-html/unnamed-chunk-922-1.png" width="672"></div>
<!-- ======================================================= -->
</div>
</div>
<div id="phân-tích-bằng-hồi-quy-cox" class="section level2" number="27.5">
<h2>
<span class="header-section-number">27.5</span> Phân tích bằng hồi quy Cox<a class="anchor" aria-label="anchor" href="#ph%C3%A2n-t%C3%ADch-b%E1%BA%B1ng-h%E1%BB%93i-quy-cox"><i class="fas fa-link"></i></a>
</h2>
<p>Hồi quy mối nguy theo tỷ lệ Cox (sau này sẽ gọi ngắn gọn là hồi quy Cox) là một trong những kỹ thuật hồi quy phổ biến nhất cho phân tích sống còn. Các mô hình khác cũng có thể được sử dụng, vì để sử dụng thích hợp mô hình Cox, <em>các giả định quan trọng</em> cần phải được xác minh: xem tài liệu tham khảo.</p>
<p>Trong một mô hình hồi quy Cox, đo lường ảnh hưởng là <strong><em>hazard rate (tỷ suất mối nguy)</em></strong> (HR), là nguy cơ xảy ra sự kiện (hay là nguy cơ tử vong trong ví dụ này), của người tham gia sống sót đến một thời điểm cụ thể. Thông thường, chúng ta quan tâm đến việc so sánh giữa các nhóm <em>độc lập</em> gvề nguy cơ của nó, và sử dụng tỷ số nguy cơ mà tương tự như tỷ số chênh khi thực hiện hồi quy logistic đa biến. Hàm <code>cox.ph()</code> từ package <strong>survival</strong> được sử dụng để fit mô hình. Hàm <code>cox.zph()</code> từ package <strong>survival</strong> có thể được sử dụng để kiểm tra tính phù hợp của giả định nguy cơ theo tỷ lệ với mô hình hồi quy Cox.</p>
<p><span style="color: black;"><strong><em>LƯU Ý:</em></strong> Xác suất phải nằm trong khoảng từ 0 đến 1. Tuy nhiên, nguy cơ đại điện cho số sự kiện dự đoán trên một đơn vị thời gian.</span></p>
<ul>
<li>Nếu tỷ số nguy cơ cho một yếu tố dự đoán gần bằng 1, thì yếu tố dự đoán đó không ảnh hưởng đến sự sống sót,</li>
<li>Nếu HR nhỏ hơn 1, thì yếu tố dự đoán là yếu tố bảo vệ (tức là yếu tố liên quan đến cải thiện khả năng sống sót),</li>
<li>Và nếu HR lớn hơn 1, thì yếu tố dự đoán kết hợp với tăng nguy cơ (hay là giảm khả năng sống sót).</li>
</ul>
<div id="fitting-một-mô-hình-cox" class="section level3 unnumbered">
<h3>Fitting một mô hình Cox<a class="anchor" aria-label="anchor" href="#fitting-m%E1%BB%99t-m%C3%B4-h%C3%ACnh-cox"><i class="fas fa-link"></i></a>
</h3>
<p>Đầu tiên, chúng ta có thể fit một mô hình để đánh giá ảnh hưởng của tuổi và giới lên sự sống sót. Chỉ cần xuất mô hình, chúng ta có những thông tin sau:</p>
<ul>
<li>các ước lượng hệ số hồi quy <code>coef</code> để xác định mối liên hệ giữa các biến dự đoán và biến kết cục,</li>
<li>lũy thừa của các ước số (<code><a href="https://rdrr.io/r/base/Log.html">exp(coef)</a></code>) để tính <em>tỷ số nguy cơ</em>,</li>
<li>các sai số chuẩn <code>se(coef)</code>,</li>
<li>chỉ số z-score: bao nhiêu sai số chuẩn là hệ số ước tính khác biệt từ giá trị 0,</li>
<li>và p-value: xác suất mà ước số có thể là 0.</li>
</ul>
<p>Áp dụng hàm <code><a href="https://rdrr.io/r/base/summary.html">summary()</a></code> cho các đối tượng của mô hình Cox cho biết thêm thông tin như là khoảng tin cậy của HR và các chỉ số kiểm định khác.</p>
<p>Kết quả của hiệp biến đầu tiên <code>gender</code> được trình bày ở hàng đầu tiên. <code>genderm</code> (nam) được in ra có ngụ ý rằng vị trí tầng đầu tiên (“f”), tức là nhóm nữ, là nhóm tham chiếu cho biến số giới tính. Vì thế, giải thích các thông số kiểm định là của nam so với nữ. Giá trị p chỉ ra rằng không có đủ bằng chứng về ảnh hưởng của giới tính lên mối nguy hay là không có đủ bằng chứng về mối liên quan giữa giới và tử vong (do tất cả các nguyên nhân).</p>
<p>Cũng thiếu bằng chứng như vậy đối với biến số nhóm tuổi.</p>
<div class="sourceCode" id="cb1304"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co">#fitting the cox model</span>
<span class="va">linelistsurv_cox_sexage</span> <span class="op">&lt;-</span>  <span class="fu">survival</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/survival/man/coxph.html">coxph</a></span><span class="op">(</span>
              <span class="fu">Surv</span><span class="op">(</span><span class="va">futime</span>, <span class="va">event</span><span class="op">)</span> <span class="op">~</span> <span class="va">gender</span> <span class="op">+</span> <span class="va">age_cat_small</span>, 
              data <span class="op">=</span> <span class="va">linelist_surv</span>
              <span class="op">)</span>


<span class="co">#printing the model fitted</span>
<span class="va">linelistsurv_cox_sexage</span></code></pre></div>
<pre><code>## Call:
## survival::coxph(formula = Surv(futime, event) ~ gender + age_cat_small, 
##     data = linelist_surv)
## 
##                       coef exp(coef) se(coef)      z     p
## genderm           -0.03149   0.96900  0.04767 -0.661 0.509
## age_cat_small5-19  0.09400   1.09856  0.06454  1.456 0.145
## age_cat_small20+   0.05032   1.05161  0.06953  0.724 0.469
## 
## Likelihood ratio test=2.8  on 3 df, p=0.4243
## n= 4321, number of events= 1853 
##    (218 observations deleted due to missingness)</code></pre>
<div class="sourceCode" id="cb1306"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co">#summary of the model</span>
<span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">linelistsurv_cox_sexage</span><span class="op">)</span></code></pre></div>
<pre><code>## Call:
## survival::coxph(formula = Surv(futime, event) ~ gender + age_cat_small, 
##     data = linelist_surv)
## 
##   n= 4321, number of events= 1853 
##    (218 observations deleted due to missingness)
## 
##                       coef exp(coef) se(coef)      z Pr(&gt;|z|)
## genderm           -0.03149   0.96900  0.04767 -0.661    0.509
## age_cat_small5-19  0.09400   1.09856  0.06454  1.456    0.145
## age_cat_small20+   0.05032   1.05161  0.06953  0.724    0.469
## 
##                   exp(coef) exp(-coef) lower .95 upper .95
## genderm               0.969     1.0320    0.8826     1.064
## age_cat_small5-19     1.099     0.9103    0.9680     1.247
## age_cat_small20+      1.052     0.9509    0.9176     1.205
## 
## Concordance= 0.514  (se = 0.007 )
## Likelihood ratio test= 2.8  on 3 df,   p=0.4
## Wald test            = 2.78  on 3 df,   p=0.4
## Score (logrank) test = 2.78  on 3 df,   p=0.4</code></pre>
<p>Thật rất thú vị để thực hiện mô hình và xem kết quả, nhưng quan sát đầu tiên để xác minh xem có thỏa các giả định về nguy cơ theo tỷ lệ hay không mà có thể giúp tiết kiệm thời gian.</p>
<div class="sourceCode" id="cb1308"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">test_ph_sexage</span> <span class="op">&lt;-</span> <span class="fu">survival</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/survival/man/cox.zph.html">cox.zph</a></span><span class="op">(</span><span class="va">linelistsurv_cox_sexage</span><span class="op">)</span>
<span class="va">test_ph_sexage</span></code></pre></div>
<pre><code>##               chisq df    p
## gender        0.454  1 0.50
## age_cat_small 0.838  2 0.66
## GLOBAL        1.399  3 0.71</code></pre>
<p><span style="color: black;"><strong><em>LƯU Ý:</em></strong> đối số thứ hai được gọi là <em>method</em> có thể được định rõ khi tính toán mô hình Cox để xác định cách ràng buộc được vận dụng. Phương pháp <em>mặc định</em> là “efron”, và các tùy chọn khác là “breslow” và “exact”.</span></p>
<p>Trong một mô hình khác, chúng tôi thêm nhiều yếu tố nguy cơ hơn như nguồn lây và số ngày giữa ngày khởi phát và ngày nhập viện. Điều trước tiên vào lúc này là xác minh các giả định nguy cơ theo tỷ lệ trước khi thực hiện các bước tiếp theo.</p>
<p>Trong mô hình này, chúng ta bao gồm một biến dự báo liên tục (<code>days_onset_hosp</code>). Trong trường hợp này, chúng ta giải thích các ước tính của thông số như là sự gia tăng theo lôgarít kỳ vọng của nguy cơ tương đối cho mỗi mức tăng của một đơn vị trong biến dự đoán, bằng cách giữ các yếu tố dự đoán khác cố định. Đầu tiên chúng ta xác minh giả định nguy cơ theo tỷ lệ.</p>
<div class="sourceCode" id="cb1310"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co">#fit the model</span>
<span class="va">linelistsurv_cox</span> <span class="op">&lt;-</span>  <span class="fu">coxph</span><span class="op">(</span>
                        <span class="fu">Surv</span><span class="op">(</span><span class="va">futime</span>, <span class="va">event</span><span class="op">)</span> <span class="op">~</span> <span class="va">gender</span> <span class="op">+</span> <span class="va">age_years</span><span class="op">+</span> <span class="va">source</span> <span class="op">+</span> <span class="va">days_onset_hosp</span>,
                        data <span class="op">=</span> <span class="va">linelist_surv</span>
                        <span class="op">)</span>


<span class="co">#test the proportional hazard model</span>
<span class="va">linelistsurv_ph_test</span> <span class="op">&lt;-</span> <span class="fu">cox.zph</span><span class="op">(</span><span class="va">linelistsurv_cox</span><span class="op">)</span>
<span class="va">linelistsurv_ph_test</span></code></pre></div>
<pre><code>##                    chisq df       p
## gender           0.45062  1    0.50
## age_years        0.00199  1    0.96
## source           1.79622  1    0.18
## days_onset_hosp 31.66167  1 1.8e-08
## GLOBAL          34.08502  4 7.2e-07</code></pre>
<p>Việc xác minh bằng đồ thị của giả định này có thể được thực hiện bằng hàm <code>ggcoxzph()</code> của package <strong>survminer</strong>.</p>
<div class="sourceCode" id="cb1312"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu">survminer</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/survminer/man/ggcoxzph.html">ggcoxzph</a></span><span class="op">(</span><span class="va">linelistsurv_ph_test</span><span class="op">)</span></code></pre></div>
<div class="inline-figure"><img src="_main_files/figure-html/unnamed-chunk-923-1.png" width="672"></div>
<p>Kết quả mô hình chỉ ra rằng có mối liên quan nghịch giữa khoảng thời gian từ khởi phát bệnh đến nhân viện và tử vong do tất cả các nguyên nhân. Nguy cơ dự đoán là bằng 0.9 lần ở một người nhập viện trễ hơn một ngày so với người khác, khi giữ biến giới tính cố định. Hay giải thích một cách dễ hiểu hơn, tăng một đơn vị thời gian từ lúc khởi phát đến nhập viện thì có liên quan đến giảm 10.7% (<code>coef *100</code>) nguy cơ tử vong.</p>
<p>Kết quả cũng cho thấy một mối liên quan thuận giữa nguồn lây và tử vong. Điều này có nghĩa là nguy cơ tử vong của bệnh nhân có nguồn lây bằng 1.21 lần so với bệnh nhân có nguồn lây là đám tang.</p>
<div class="sourceCode" id="cb1313"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co">#print the summary of the model</span>
<span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">linelistsurv_cox</span><span class="op">)</span></code></pre></div>
<pre><code>## Call:
## coxph(formula = Surv(futime, event) ~ gender + age_years + source + 
##     days_onset_hosp, data = linelist_surv)
## 
##   n= 2772, number of events= 1180 
##    (1767 observations deleted due to missingness)
## 
##                      coef exp(coef)  se(coef)      z Pr(&gt;|z|)    
## genderm          0.004710  1.004721  0.060827  0.077   0.9383    
## age_years       -0.002249  0.997753  0.002421 -0.929   0.3528    
## sourceother      0.178393  1.195295  0.084291  2.116   0.0343 *  
## days_onset_hosp -0.104063  0.901169  0.014245 -7.305 2.77e-13 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
##                 exp(coef) exp(-coef) lower .95 upper .95
## genderm            1.0047     0.9953    0.8918    1.1319
## age_years          0.9978     1.0023    0.9930    1.0025
## sourceother        1.1953     0.8366    1.0133    1.4100
## days_onset_hosp    0.9012     1.1097    0.8764    0.9267
## 
## Concordance= 0.566  (se = 0.009 )
## Likelihood ratio test= 71.31  on 4 df,   p=1e-14
## Wald test            = 59.22  on 4 df,   p=4e-12
## Score (logrank) test = 59.54  on 4 df,   p=4e-12</code></pre>
<p>Chúng ta có thể xác minh mối quan hệ này bằng một bảng:</p>
<div class="sourceCode" id="cb1315"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">linelist_case_data</span> <span class="op">%&gt;%</span> 
  <span class="fu">tabyl</span><span class="op">(</span><span class="va">days_onset_hosp</span>, <span class="va">outcome</span><span class="op">)</span> <span class="op">%&gt;%</span> 
  <span class="fu">adorn_percentages</span><span class="op">(</span><span class="op">)</span> <span class="op">%&gt;%</span>  
  <span class="fu">adorn_pct_formatting</span><span class="op">(</span><span class="op">)</span></code></pre></div>
<pre><code>##  days_onset_hosp Death Recover   NA_
##                0 44.3%   31.4% 24.3%
##                1 46.6%   32.2% 21.2%
##                2 43.0%   32.8% 24.2%
##                3 45.0%   32.3% 22.7%
##                4 41.5%   38.3% 20.2%
##                5 40.0%   36.2% 23.8%
##                6 32.2%   48.7% 19.1%
##                7 31.8%   38.6% 29.5%
##                8 29.8%   38.6% 31.6%
##                9 30.3%   51.5% 18.2%
##               10 16.7%   58.3% 25.0%
##               11 36.4%   45.5% 18.2%
##               12 18.8%   62.5% 18.8%
##               13 10.0%   60.0% 30.0%
##               14 10.0%   50.0% 40.0%
##               15 28.6%   42.9% 28.6%
##               16 20.0%   80.0%  0.0%
##               17  0.0%  100.0%  0.0%
##               18  0.0%  100.0%  0.0%
##               22  0.0%  100.0%  0.0%
##               NA 52.7%   31.2% 16.0%</code></pre>
<p>Chúng ta cần phải xem xét và điều tra tại sao sự kết hợp này tồn tại trong số liệu. Một giải thích có thể chấp nhận được là bệnh nhân nhập viện trễ hơn vì có bệnh lúc đầu ít nghiêm trọng hơn. Một giải thích khác có lẽ dễ chấp nhận hơn là vì chúng ta sử dụng một bộ số liệu mô phỏng, mẫu này không phản ánh đúng thực tế!</p>
<!-- ======================================================= -->
</div>
<div id="biểu-đồ-forest-plot-1" class="section level3 unnumbered">
<h3>Biểu đồ Forest plot<a class="anchor" aria-label="anchor" href="#bi%E1%BB%83u-%C4%91%E1%BB%93-forest-plot-1"><i class="fas fa-link"></i></a>
</h3>
<p>Chúng ta có thể vẽ kết quả của mô hình Cox bằng cách sử dụng hàm <code>ggforest()</code> trong package <strong>survminer</strong> để vẽ biểu đồ Forest plot.</p>
<div class="sourceCode" id="cb1317"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu">ggforest</span><span class="op">(</span><span class="va">linelistsurv_cox</span>, data <span class="op">=</span> <span class="va">linelist_surv</span><span class="op">)</span></code></pre></div>
<div class="inline-figure"><img src="_main_files/figure-html/forestp-1.png" width="672"></div>
<!-- ======================================================= -->
</div>
</div>
<div id="các-hiệp-biến-phụ-thuộc-vào-thời-gian-trong-mô-hình-sống-còn" class="section level2" number="27.6">
<h2>
<span class="header-section-number">27.6</span> Các hiệp biến phụ thuộc vào thời gian trong mô hình sống còn<a class="anchor" aria-label="anchor" href="#c%C3%A1c-hi%E1%BB%87p-bi%E1%BA%BFn-ph%E1%BB%A5-thu%E1%BB%99c-v%C3%A0o-th%E1%BB%9Di-gian-trong-m%C3%B4-h%C3%ACnh-s%E1%BB%91ng-c%C3%B2n"><i class="fas fa-link"></i></a>
</h2>
<p>Một số nội dung dưới đây được adapt từ tài liệu <a href="https://www.emilyzabor.com/tutorials/survival_analysis_in_r_tutorial.html">Giới thiệu về phân tích sống còn với R</a> với sự cho phép của <a href="https://www.emilyzabor.com/">TS. Emily Zabor</a></p>
<p>Trong phần trước, chúng ta đã đề cập đến việc sử dụng hồi quy Cox để kiểm tra mối liên quan giữa hiệp biến và biến kết cục sống còn. Nhưng những phân tích này dựa trên hiệp biến được đo lường ở thời điểm ban đầu, tức là trước thời gian theo dõi sự kiện bắt đầu.</p>
<p>Điều gì sẽ xảy ra nếu chúng ta quan tâm đến một hiệp biến được đo <strong>sau khi</strong> thời gian theo dõi bắt đầu? Hoặc điều gì sẽ xảy ra nếu chúng ta có một hiệp biến có thể thay đổi theo thời gian</p>
<p>Ví dụ: có thể chúng ta đang làm việc với các số liệu lâm sàng mà chúng lặp lại đo lường các giá trị xét nghiệm mà có thể thay đổi theo thời gian. Đây là một ví dụ về <strong>hiệp biến phụ thuộc vào thời gian</strong>. Để nhấn mạnh vào vấn đề này, chúng ta cần một thiết lập đặc biệt, nhưng may là mô hình Cox rất linh động và loại số liệu này cũng có thể được mô hình hóa bằng các công cụ từ package <strong>survival</strong>.</p>
<div id="thiết-lập-hiệp-biến-phụ-thuộc-vào-thời-gian" class="section level3 unnumbered">
<h3>Thiết lập hiệp biến phụ thuộc vào thời gian<a class="anchor" aria-label="anchor" href="#thi%E1%BA%BFt-l%E1%BA%ADp-hi%E1%BB%87p-bi%E1%BA%BFn-ph%E1%BB%A5-thu%E1%BB%99c-v%C3%A0o-th%E1%BB%9Di-gian"><i class="fas fa-link"></i></a>
</h3>
<p>Phân tích các hiệp biến phụ thuộc vào thời gian trong R đòi hỏi thiết lập một bộ dữ liệu đặc biệt. Nếu quan tâm, hãy xem chi tiết hơn về vấn đề này được viết bởi tác giả của package <strong>survival</strong> <a href="https://cran.r-project.org/web/packages/survival/vignettes/timedep.pdf">Sử Dụng Hiệp Biến Phụ Thuộc Vào Thời Gian và Hệ Số Phụ Thuộc Vào Thời Gian trong Mô Hình Cox</a>.</p>
<p>Đối với vấn đề này, chúng ta sử dụng một bộ số liệu mới từ package <code>SemiCompRisks</code> có tên là <code>BMT</code>, bộ số liệu này bao gồm 137 bệnh nhân cấy ghép tủy xương. Các biến chúng ta sẽ tập trung vào là:</p>
<ul>
<li>
<code>T1</code> - thời gian (tính bằng ngày) đến khi tử vong hoặc đến lần theo dõi cuối cùng<br>
</li>
<li>
<code>delta1</code> - chỉ số tử vong; 1-Tử vong, 0-Còn sống<br>
</li>
<li>
<code>TA</code> - thời gian (tính theo ngày) đến khi phát bệnh GVHD cấp tính (bệnh tế bào ghép tấn công vật chủ)<br>
</li>
<li>
<code>deltaA</code> - chỉ số của bệnh GVHD cấp tính;
<ul>
<li>1 - Đã tiến triển bệnh GVHD cấp tính<br>
</li>
<li>0 - Không tiến triển bệnh GVHD cấp tính</li>
</ul>
</li>
</ul>
<p>Chúng ta sẽ gọi bộ số liệu này từ package <strong>survival</strong> bằng cách sử dụng lệnh <code><a href="https://rdrr.io/r/utils/data.html">data()</a></code> từ <strong>base</strong> R, giúp tải số liệu được chứa ở trong một package đã được cài đặt. Một data frame có tên <code>BMT</code> sẽ hiện thị trong môi trường R.</p>
<div class="sourceCode" id="cb1318"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/utils/data.html">data</a></span><span class="op">(</span><span class="va">BMT</span>, package <span class="op">=</span> <span class="st">"SemiCompRisks"</span><span class="op">)</span></code></pre></div>
<div id="thêm-mã-nhận-dạng-bệnh-nhân" class="section level4 unnumbered">
<h4>Thêm mã nhận dạng bệnh nhân<a class="anchor" aria-label="anchor" href="#th%C3%AAm-m%C3%A3-nh%E1%BA%ADn-d%E1%BA%A1ng-b%E1%BB%87nh-nh%C3%A2n"><i class="fas fa-link"></i></a>
</h4>
<p>Không có cột ID trong bộ số liệu <code>BMT</code>, cột này cần thiết để tạo ra bộ số liệu mà chúng ta muốn. Vì vậy, chúng ta sử dụng hàm <code>rowid_to_column()</code> từ package <strong>tibble</strong> thuộc hệ sinh thái <strong>tidyverse</strong> để tạo một biến id mới gọi là <code>my_id</code> (thêm cột ở vị trí đầu tiên của bộ số liệu với việc đánh số hàng tuần tự theo số nhận dạng bắt đầu từ số 1). Chúng ta đặt tên bộ số liệu này là <code>bmt</code>.</p>
<div class="sourceCode" id="cb1319"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">bmt</span> <span class="op">&lt;-</span> <span class="fu">rowid_to_column</span><span class="op">(</span><span class="va">BMT</span>, <span class="st">"my_id"</span><span class="op">)</span></code></pre></div>
<p>Bộ số liệu mới bây giờ trông sẽ như thế này:</p>
<div id="htmlwidget-79eee608513a05053405" style="width:100%;height:auto;" class="datatables html-widget"></div>
<script type="application/json" data-for="htmlwidget-79eee608513a05053405">{"x":{"filter":"none","data":[[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,123,124,125,126,127,128,129,130,131,132,133,134,135,136,137],[1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3],[2081,1602,1496,1462,1433,1377,1330,996,226,1199,1111,530,1182,1167,418,417,276,156,781,172,487,716,194,371,526,122,1279,110,243,86,466,262,162,262,1,107,269,350,2569,2506,2409,2218,1857,1829,1562,1470,1363,1030,860,1258,2246,1870,1799,1709,1674,1568,1527,1324,957,932,847,848,1850,1843,1535,1447,1384,414,2204,1063,481,105,641,390,288,522,79,1156,583,48,431,1074,393,10,53,80,35,1499,704,653,222,1356,2640,2430,2252,2140,2133,1238,1631,2024,1345,1136,845,491,162,1298,121,2,62,265,547,341,318,195,469,93,515,183,105,128,164,129,122,80,677,73,168,74,16,248,732,105,392,63,97,153,363],[2081,1602,1496,1462,1433,1377,1330,996,226,1199,1111,530,1182,1167,418,383,276,104,609,172,487,662,194,230,526,122,129,74,122,86,466,192,109,55,1,107,110,332,2569,2506,2409,2218,1857,1829,1562,1470,1363,1030,860,1258,2246,1870,1799,1709,1674,1568,1527,1324,957,932,847,848,1850,1843,1535,1447,1384,414,2204,1063,481,105,641,390,288,421,79,748,486,48,272,1074,381,10,53,80,35,248,704,211,219,606,2640,2430,2252,2140,2133,1238,1631,2024,1345,1136,845,422,162,84,100,2,47,242,456,268,318,32,467,47,390,183,105,115,164,93,120,80,677,64,168,74,16,157,625,48,273,63,76,113,363],[0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1],[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,1,0,0,1,0,1,0,0,1,1,1,0,0,1,1,1,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,1,0,1,0,1,0,0,0,0,1,0,1,1,1,0,0,0,0,0,0,0,0,0,0,0,1,0,1,1,0,1,1,1,1,0,1,1,1,1,0,0,1,0,1,1,0,0,1,0,0,0,1,1,1,1,0,1,1,0],[0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1],[67,1602,1496,70,1433,1377,1330,72,226,1199,1111,38,1182,39,418,417,276,28,781,22,487,716,194,371,526,88,1279,110,243,86,466,10,162,262,1,107,269,350,2569,2506,2409,2218,1857,1829,1562,1470,1363,1030,860,1258,52,1870,1799,20,1674,1568,1527,25,957,29,847,848,1850,1843,1535,1447,1384,414,2204,1063,30,21,641,390,18,25,16,1156,583,48,431,1074,393,10,53,10,35,1499,36,653,222,1356,2640,2430,2252,2140,2133,1238,1631,2024,32,1136,845,491,162,1298,28,2,62,265,547,21,318,195,469,93,515,183,105,128,164,129,122,21,677,73,168,29,16,248,732,105,392,38,97,153,363],[1,0,0,1,0,0,0,1,0,0,0,1,0,1,0,0,0,1,0,1,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,1,1,0,0,1,1,1,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,1,0,0,0],[121,139,307,95,236,123,96,121,226,91,1111,84,112,487,220,417,81,156,781,172,76,716,94,184,121,122,1279,110,243,86,119,84,162,262,1,107,120,350,2569,2506,2409,2218,260,1829,1562,180,200,210,860,120,380,230,140,348,1674,1568,1527,1324,957,932,847,155,1850,1843,1535,220,200,414,2204,240,120,105,641,390,100,140,79,180,583,48,431,120,100,10,53,80,35,1499,155,653,123,1356,2640,2430,150,220,250,250,150,180,360,140,845,180,162,1298,121,2,62,210,130,100,140,195,90,93,515,130,105,128,164,129,122,80,150,73,200,74,16,100,732,105,122,63,97,153,363],[1,1,1,1,1,1,1,1,0,1,0,1,1,1,1,0,1,0,0,0,1,0,1,1,1,0,0,0,0,0,1,1,0,0,0,0,1,0,0,0,0,0,1,0,0,1,1,1,0,1,1,1,1,1,0,0,0,0,0,0,0,1,0,0,0,1,1,0,0,1,1,0,0,0,1,1,0,1,0,0,0,1,1,0,0,0,0,0,1,0,1,0,0,0,1,1,1,1,1,1,1,1,0,1,0,0,0,0,0,1,1,1,1,0,1,0,0,1,0,0,0,0,0,0,1,0,1,0,0,1,0,0,1,0,0,0,0],[13,18,12,13,12,12,17,12,10,29,22,34,22,1167,21,16,21,20,26,37,22,17,25,9,11,13,22,49,23,86,100,59,40,24,1,107,27,33,21,17,16,11,15,19,18,14,12,14,15,66,15,16,12,19,24,14,13,15,69,7,16,16,9,19,21,24,19,27,12,16,24,15,11,11,288,20,79,18,11,14,12,19,16,10,53,80,35,9,18,23,52,14,22,14,17,18,17,18,40,16,14,15,20,491,13,1298,65,2,11,14,24,17,12,16,20,28,31,21,105,12,164,51,12,0,8,38,48,24,16,52,18,30,24,16,97,59,19],[1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,0,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,0,1,1,1,1,1,1,0,0,0,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,0,1,0,1,1,1,1,1,1,1,1,1,1,0,1,0,1,1,1,1,1,1,1,0,1,1,1,1,1,0,1,1],[26,21,26,17,32,22,20,22,18,24,19,17,24,27,18,15,18,20,27,40,22,28,26,39,15,20,17,28,37,17,15,29,36,23,42,30,29,22,19,31,35,16,29,19,26,27,13,25,25,30,45,33,32,23,37,15,22,46,18,27,28,23,37,34,35,33,21,21,25,50,35,37,26,50,45,28,43,14,17,32,30,30,33,34,33,30,23,35,29,23,28,33,18,29,35,27,36,24,27,35,50,47,40,22,22,8,39,20,27,32,31,20,35,36,35,7,23,11,14,37,19,37,25,35,15,45,32,41,27,33,39,17,43,44,48,31,52],[33,37,35,21,36,31,17,24,21,40,28,28,23,22,14,20,5,33,27,37,20,32,32,31,20,26,20,25,38,26,18,32,43,16,48,19,20,20,13,34,31,16,35,18,30,34,24,29,31,16,39,30,23,28,34,19,12,31,17,30,29,26,36,32,32,28,18,15,19,38,36,34,24,48,43,30,43,19,14,33,23,32,28,54,41,35,25,18,21,16,30,22,23,26,31,17,39,28,21,41,36,27,39,21,23,2,48,19,25,32,28,23,40,39,33,2,25,7,18,35,32,34,29,28,14,42,43,29,36,39,43,14,50,37,56,25,48],[1,1,1,0,1,1,1,1,0,1,1,1,0,0,1,1,0,1,1,0,1,1,0,0,1,1,0,1,0,1,1,1,1,0,1,1,0,1,1,1,1,1,0,1,1,1,1,0,0,0,0,0,1,0,1,1,0,1,1,0,1,1,0,0,0,0,0,1,0,1,1,1,1,1,1,1,0,1,0,0,0,1,0,1,0,0,0,1,0,1,1,1,1,1,1,1,0,1,1,0,1,1,0,0,1,0,1,1,1,1,1,0,0,1,0,1,1,0,1,0,0,0,0,1,1,0,0,0,0,0,0,0,1,1,1,0,1],[0,1,1,1,1,1,0,0,1,1,1,1,0,1,1,1,0,1,0,0,1,1,1,1,1,0,0,0,1,0,1,1,1,1,1,1,1,0,1,1,1,1,0,1,1,1,1,0,1,1,0,0,0,1,1,0,1,1,1,0,1,1,0,0,1,1,0,1,0,0,0,0,1,1,1,1,0,0,1,1,1,1,0,0,1,0,1,1,1,0,1,1,1,1,0,1,1,0,0,1,1,0,0,0,0,0,1,1,1,0,0,1,1,1,0,1,1,1,0,0,0,1,1,0,1,1,1,1,0,0,1,1,1,1,1,1,1],[1,0,1,0,1,1,1,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,1,1,1,0,1,1,1,0,1,1,0,1,0,1,1,1,1,1,0,1,0,0,1,0,1,0,1,0,0,0,1,0,0,0,0,0,1,0,1,0,0,0,1,1,1,0,0,1,0,0,0,0,1,1,1,0,1,1,0,1,0,1,0,1,1,0,0,0,1,0,1,1,0,1,1,1,0,0,1,1,0,0,0,1,1,1,0,1,0,1,0,0,1,0,1,1,0,1,1,1,1,1,1,1,0,1,0,1,1,1],[1,0,0,0,1,1,1,0,0,1,1,0,1,1,0,0,0,1,1,1,0,0,0,1,0,1,0,0,1,0,0,0,0,1,0,1,1,0,0,0,1,0,0,0,1,1,0,0,1,0,0,1,0,0,0,0,1,1,0,0,0,0,1,1,0,1,0,1,1,0,1,1,0,0,1,1,0,0,0,0,0,0,0,1,1,1,1,1,0,0,1,0,0,1,0,1,0,1,0,0,1,0,1,0,1,0,1,0,0,0,1,1,1,0,0,0,0,0,0,1,1,0,1,0,0,0,1,1,0,1,1,0,0,0,1,1,0],[98,1720,127,168,93,2187,1006,1319,208,174,236,151,203,191,110,824,146,85,187,129,128,84,329,147,943,2616,937,303,170,239,508,74,393,331,196,178,361,834,270,60,120,60,90,210,90,240,90,210,180,180,105,225,120,90,60,90,450,75,90,60,75,180,180,270,180,150,120,120,60,270,90,120,90,120,90,90,90,60,120,150,120,150,120,240,180,150,150,30,105,90,120,210,750,24,120,210,240,240,690,105,120,900,210,210,300,105,210,75,90,180,630,180,300,90,120,135,210,120,150,270,285,240,510,780,150,180,150,750,180,180,150,210,240,360,330,240,180],[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,1,0,1,0,0,1,0,0,0,0,1,0,0,1,0,1,1,0,0,0,0,1,0,0,0,1,1,1,1,0,0,0,0,0,0,1,1,1,0,0,0,0,0,0,1,1,0,0,1,1,0,1,1,1,1,1,1,1,0,1,0,1,1,1,1,0,1,1,1,1,1,1,1,0,0,1,1,1,0,1,0,0,0],[1,1,1,1,1,1,1,1,1,3,3,3,2,2,1,1,1,1,1,1,1,1,1,1,1,1,3,3,3,3,3,3,2,2,2,2,2,2,1,1,1,1,1,1,1,1,1,1,1,2,4,4,4,4,4,4,4,4,4,4,4,4,3,3,3,3,3,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,2,2,2,2,4,4,4,3,3,1,1,1,1,1,1,2,4,4,3,3,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,2,2,2,4,4,4,4,3,3,3,3,3],[0,0,0,0,0,0,0,0,0,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,1,1,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,0,0,0,1,1,0,0,0,0,0,0,1,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,0,0,0,0,1,1,1,1,1]],"container":"<table class=\"white-space: nowrap\">\n  <thead>\n    <tr>\n      <th>my_id<\/th>\n      <th>g<\/th>\n      <th>T1<\/th>\n      <th>T2<\/th>\n      <th>delta1<\/th>\n      <th>delta2<\/th>\n      <th>delta3<\/th>\n      <th>TA<\/th>\n      <th>deltaA<\/th>\n      <th>TC<\/th>\n      <th>deltaC<\/th>\n      <th>TP<\/th>\n      <th>deltaP<\/th>\n      <th>Z1<\/th>\n      <th>Z2<\/th>\n      <th>Z3<\/th>\n      <th>Z4<\/th>\n      <th>Z5<\/th>\n      <th>Z6<\/th>\n      <th>Z7<\/th>\n      <th>Z8<\/th>\n      <th>Z9<\/th>\n      <th>Z10<\/th>\n    <\/tr>\n  <\/thead>\n<\/table>","options":{"pageLength":5,"scrollX":true,"columnDefs":[{"className":"dt-right","targets":[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22]}],"order":[],"autoWidth":false,"orderClasses":false,"lengthMenu":[5,10,25,50,100]}},"evals":[],"jsHooks":[]}</script>
</div>
<div id="mở-rộng-hàng-của-các-bệnh-nhân" class="section level4 unnumbered">
<h4>Mở rộng hàng của các bệnh nhân<a class="anchor" aria-label="anchor" href="#m%E1%BB%9F-r%E1%BB%99ng-h%C3%A0ng-c%E1%BB%A7a-c%C3%A1c-b%E1%BB%87nh-nh%C3%A2n"><i class="fas fa-link"></i></a>
</h4>
<p>Tiếp theo, chúng ta sử dụng hàm <code>tmerge()</code> với các hàm hỗ trợ <code>event()</code> và <code>tdc()</code> để tái cấu trúc bộ số liệu. Mục tiêu của chúng ta là tái cấu trúc bộ số liệu để tạo một hàng riêng biệt cho từng bệnh nhân trong mỗi khoảng thời gian mà họ có giá trị <code>deltaA</code> khác nhau. Trong bộ số liệu này, mỗi bệnh nhân có thể có nhiều nhất là hai hàng tùy thuộc vào việc họ có phát bệnh GVHD hay không trong giai đoạn thu thập số liệu. Chúng ta sẽ gọi chỉ số mới cho việc phát bệnh GVHD là <code>agvhd</code>.</p>
<ul>
<li>
<code>tmerge()</code> tạo một bộ số liệu dài với nhiều khoảng thời gian cho các giá trị hiệp biến khác nhau cho từng bệnh nhân</li>
<li>
<code>event()</code> tạo chỉ số cho sự kiện mới để đi cùng với khoảng thời gian mới được tạo ra</li>
<li>
<code>tdc()</code> tạo cột hiệp biến phụ thuộc vào thời gian <code>agvhd</code> để đi cùng với các khoảng thời gian mới được tạo ra</li>
</ul>
<div class="sourceCode" id="cb1320"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">td_dat</span> <span class="op">&lt;-</span> 
  <span class="fu">tmerge</span><span class="op">(</span>
    data1 <span class="op">=</span> <span class="va">bmt</span> <span class="op">%&gt;%</span> <span class="fu">select</span><span class="op">(</span><span class="va">my_id</span>, <span class="va">T1</span>, <span class="va">delta1</span><span class="op">)</span>, 
    data2 <span class="op">=</span> <span class="va">bmt</span> <span class="op">%&gt;%</span> <span class="fu">select</span><span class="op">(</span><span class="va">my_id</span>, <span class="va">T1</span>, <span class="va">delta1</span>, <span class="va">TA</span>, <span class="va">deltaA</span><span class="op">)</span>, 
    id <span class="op">=</span> <span class="va">my_id</span>, 
    death <span class="op">=</span> <span class="fu">event</span><span class="op">(</span><span class="va">T1</span>, <span class="va">delta1</span><span class="op">)</span>,
    agvhd <span class="op">=</span> <span class="fu">tdc</span><span class="op">(</span><span class="va">TA</span><span class="op">)</span>
    <span class="op">)</span></code></pre></div>
<p>Để xem điều này thực hiện thế nào, hãy xem số liệu của 5 bệnh nhân đầu tiên.</p>
<p>Các biến quan tâm trong bộ số liệu gốc trông như sau:</p>
<div class="sourceCode" id="cb1321"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">bmt</span> <span class="op">%&gt;%</span> 
  <span class="fu">select</span><span class="op">(</span><span class="va">my_id</span>, <span class="va">T1</span>, <span class="va">delta1</span>, <span class="va">TA</span>, <span class="va">deltaA</span><span class="op">)</span> <span class="op">%&gt;%</span> 
  <span class="fu"><a href="https://rdrr.io/r/stats/filter.html">filter</a></span><span class="op">(</span><span class="va">my_id</span> <span class="op">%in%</span> <span class="fu"><a href="https://rdrr.io/r/base/seq.html">seq</a></span><span class="op">(</span><span class="fl">1</span>, <span class="fl">5</span><span class="op">)</span><span class="op">)</span></code></pre></div>
<pre><code>##   my_id   T1 delta1   TA deltaA
## 1     1 2081      0   67      1
## 2     2 1602      0 1602      0
## 3     3 1496      0 1496      0
## 4     4 1462      0   70      1
## 5     5 1433      0 1433      0</code></pre>
<p>Bộ số liệu mới cho cùng các bệnh nhân này trông như sau:</p>
<div class="sourceCode" id="cb1323"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">td_dat</span> <span class="op">%&gt;%</span> 
  <span class="fu"><a href="https://rdrr.io/r/stats/filter.html">filter</a></span><span class="op">(</span><span class="va">my_id</span> <span class="op">%in%</span> <span class="fu"><a href="https://rdrr.io/r/base/seq.html">seq</a></span><span class="op">(</span><span class="fl">1</span>, <span class="fl">5</span><span class="op">)</span><span class="op">)</span></code></pre></div>
<pre><code>##   my_id   T1 delta1 id tstart tstop death agvhd
## 1     1 2081      0  1      0    67     0     0
## 2     1 2081      0  1     67  2081     0     1
## 3     2 1602      0  2      0  1602     0     0
## 4     3 1496      0  3      0  1496     0     0
## 5     4 1462      0  4      0    70     0     0
## 6     4 1462      0  4     70  1462     0     1
## 7     5 1433      0  5      0  1433     0     0</code></pre>
<p>Bây giờ, một số bệnh nhân có hai hàng trong bộ số liệu tương ứng với khoảng thời gian mà họ có giá trị khác của biến mới <code>agvhd</code>. Ví dụ như Bệnh nhân số 1 hiện có hai hàng có giá trị của biến <code>agvhd</code> bằng 0 từ thời điểm 0 đến 67 và giá trị bằng 1 từ thời điểm 67 đến 2081.</p>
</div>
</div>
<div id="hồi-quy-cox-với-hiệp-biến-phụ-thuộc-vào-thời-gian" class="section level3 unnumbered">
<h3>Hồi quy Cox với hiệp biến phụ thuộc vào thời gian<a class="anchor" aria-label="anchor" href="#h%E1%BB%93i-quy-cox-v%E1%BB%9Bi-hi%E1%BB%87p-bi%E1%BA%BFn-ph%E1%BB%A5-thu%E1%BB%99c-v%C3%A0o-th%E1%BB%9Di-gian"><i class="fas fa-link"></i></a>
</h3>
<p>Bây giờ, chúng ta đã định hình lại số liệu và thêm biến mới <code>aghvd</code> phụ thuộc vào thời gian, hãy fit mô hình cox đơn biến. Chúng ta có thể sử dụng cùng hàm <code>coxph()</code> như trước, chỉ cần thay đổi trong hàm <code>Surv()</code> để chỉ rõ thời gian bắt đầu và thời gian kết thúc cho mỗi khoảng thời gian bằng cách sử dụng các đối số cho <code>time1 =</code> và <code>time2 =</code>.</p>
<div class="sourceCode" id="cb1325"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">bmt_td_model</span> <span class="op">=</span> <span class="fu">coxph</span><span class="op">(</span>
  <span class="fu">Surv</span><span class="op">(</span>time <span class="op">=</span> <span class="va">tstart</span>, time2 <span class="op">=</span> <span class="va">tstop</span>, event <span class="op">=</span> <span class="va">death</span><span class="op">)</span> <span class="op">~</span> <span class="va">agvhd</span>, 
  data <span class="op">=</span> <span class="va">td_dat</span>
  <span class="op">)</span>

<span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">bmt_td_model</span><span class="op">)</span></code></pre></div>
<pre><code>## Call:
## coxph(formula = Surv(time = tstart, time2 = tstop, event = death) ~ 
##     agvhd, data = td_dat)
## 
##   n= 163, number of events= 80 
## 
##         coef exp(coef) se(coef)    z Pr(&gt;|z|)
## agvhd 0.3351    1.3980   0.2815 1.19    0.234
## 
##       exp(coef) exp(-coef) lower .95 upper .95
## agvhd     1.398     0.7153    0.8052     2.427
## 
## Concordance= 0.535  (se = 0.024 )
## Likelihood ratio test= 1.33  on 1 df,   p=0.2
## Wald test            = 1.42  on 1 df,   p=0.2
## Score (logrank) test = 1.43  on 1 df,   p=0.2</code></pre>
<p>Một lần nữa, chúng ta trực quan hóa kết quả mô hình Cox bằng cách sử dụng hàm <code>ggforest()</code> từ <strong>survminer package</strong>.:</p>
<div class="sourceCode" id="cb1327"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu">ggforest</span><span class="op">(</span><span class="va">bmt_td_model</span>, data <span class="op">=</span> <span class="va">td_dat</span><span class="op">)</span></code></pre></div>
<div class="inline-figure"><img src="_main_files/figure-html/unnamed-chunk-932-1.png" width="672"></div>
<p>Như bạn thấy từ biểu đồ forest plot, khoảng tin cậy và giá trị p cho thấy rằng không có mối liên hệ chặt chẽ giữa tử vong và bệnh GVHD cấp tính trong mô hình hồi quy đơn giản này.</p>
<!-- ======================================================= -->
</div>
</div>
<div id="tài-nguyên-học-liệu-10" class="section level2" number="27.7">
<h2>
<span class="header-section-number">27.7</span> Tài nguyên học liệu<a class="anchor" aria-label="anchor" href="#t%C3%A0i-nguy%C3%AAn-h%E1%BB%8Dc-li%E1%BB%87u-10"><i class="fas fa-link"></i></a>
</h2>
<p><a href="https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2394262/">Survival Analysis Part I: Basic concepts and first analyses</a></p>
<p><a href="https://www.emilyzabor.com/tutorials/survival_analysis_in_r_tutorial.html">Survival Analysis in R</a></p>
<p><a href="https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2954271/">Survival analysis in infectious disease research: Describing events in time</a></p>
<p><a href="https://data.princeton.edu/wws509/notes/c7.pdf">Chapter on advanced survival models Princeton</a></p>
<p><a href="https://cran.r-project.org/web/packages/survival/vignettes/timedep.pdf">Using Time Dependent Covariates and Time Dependent Coefficients in the Cox Model</a></p>
<p><a href="https://publicifsv.sund.ku.dk/~ts/survival/survival-cheat.pdf">Survival analysis cheatsheet R</a></p>
<p><a href="https://paulvanderlaken.files.wordpress.com/2017/08/survminer_cheatsheet.pdf">Survminer cheatsheet</a></p>
<p><a href="https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6322561/">Paper on different survival measures for cancer registry data with Rcode provided as supplementary materials</a></p>

</div>
</div>
  <div class="chapter-nav">
<div class="prev"><a href="survey-analysis.html"><span class="header-section-number">26</span> Phân tích khảo sát</a></div>
<div class="next"><a href="gis.html"><span class="header-section-number">28</span> GIS cơ bản</a></div>
</div></main><div class="col-md-3 col-lg-2 d-none d-md-block sidebar sidebar-chapter">
    <nav id="toc" data-toggle="toc" aria-label="On this page"><h2>On this page</h2>
      <ul class="nav navbar-nav">
<li><a class="nav-link" href="#survival-analysis"><span class="header-section-number">27</span> Phân tích sống còn</a></li>
<li><a class="nav-link" href="#t%E1%BB%95ng-quan-5"><span class="header-section-number">27.1</span> Tổng quan</a></li>
<li>
<a class="nav-link" href="#chu%E1%BA%A9n-b%E1%BB%8B-17"><span class="header-section-number">27.2</span> Chuẩn bị</a><ul class="nav navbar-nav">
<li><a class="nav-link" href="#g%E1%BB%8Di-packages-7">Gọi packages</a></li>
<li><a class="nav-link" href="#nh%E1%BA%ADp-b%E1%BB%99-s%E1%BB%91-li%E1%BB%87u">Nhập bộ số liệu</a></li>
<li><a class="nav-link" href="#qu%E1%BA%A3n-l%C3%BD-v%C3%A0-chuy%E1%BB%83n-%C4%91%E1%BB%95i-s%E1%BB%91-li%E1%BB%87u">Quản lý và chuyển đổi số liệu</a></li>
</ul>
</li>
<li>
<a class="nav-link" href="#c%C6%A1-b%E1%BA%A3n-v%E1%BB%81-ph%C3%A2n-t%C3%ADch-s%E1%BB%91ng-c%C3%B2n"><span class="header-section-number">27.3</span> Cơ bản về phân tích sống còn</a><ul class="nav navbar-nav">
<li><a class="nav-link" href="#t%E1%BA%A1o-ra-%C4%91%E1%BB%91i-t%C6%B0%E1%BB%A3ng-ki%E1%BB%83u-surv">Tạo ra đối tượng kiểu surv</a></li>
<li><a class="nav-link" href="#th%E1%BB%B1c-hi%E1%BB%87n-c%C3%A1c-ph%C3%A2n-t%C3%ADch-ban-%C4%91%E1%BA%A7u">Thực hiện các phân tích ban đầu</a></li>
<li><a class="nav-link" href="#m%E1%BB%91i-nguy-t%C3%ADch-l%C5%A9y">Mối nguy tích lũy</a></li>
<li><a class="nav-link" href="#v%E1%BA%BD-%C4%91%C6%B0%E1%BB%9Dng-cong-kaplan-meir">Vẽ đường cong Kaplan-Meir</a></li>
</ul>
</li>
<li>
<a class="nav-link" href="#so-s%C3%A1nh-c%C3%A1c-%C4%91%C6%B0%E1%BB%9Dng-cong-s%E1%BB%91ng-s%C3%B3t"><span class="header-section-number">27.4</span> So sánh các đường cong sống sót</a><ul class="nav navbar-nav"><li><a class="nav-link" href="#ki%E1%BB%83m-%C4%91%E1%BB%8Bnh-log-rank">Kiểm định Log rank</a></li></ul>
</li>
<li>
<a class="nav-link" href="#ph%C3%A2n-t%C3%ADch-b%E1%BA%B1ng-h%E1%BB%93i-quy-cox"><span class="header-section-number">27.5</span> Phân tích bằng hồi quy Cox</a><ul class="nav navbar-nav">
<li><a class="nav-link" href="#fitting-m%E1%BB%99t-m%C3%B4-h%C3%ACnh-cox">Fitting một mô hình Cox</a></li>
<li><a class="nav-link" href="#bi%E1%BB%83u-%C4%91%E1%BB%93-forest-plot-1">Biểu đồ Forest plot</a></li>
</ul>
</li>
<li>
<a class="nav-link" href="#c%C3%A1c-hi%E1%BB%87p-bi%E1%BA%BFn-ph%E1%BB%A5-thu%E1%BB%99c-v%C3%A0o-th%E1%BB%9Di-gian-trong-m%C3%B4-h%C3%ACnh-s%E1%BB%91ng-c%C3%B2n"><span class="header-section-number">27.6</span> Các hiệp biến phụ thuộc vào thời gian trong mô hình sống còn</a><ul class="nav navbar-nav">
<li><a class="nav-link" href="#thi%E1%BA%BFt-l%E1%BA%ADp-hi%E1%BB%87p-bi%E1%BA%BFn-ph%E1%BB%A5-thu%E1%BB%99c-v%C3%A0o-th%E1%BB%9Di-gian">Thiết lập hiệp biến phụ thuộc vào thời gian</a></li>
<li><a class="nav-link" href="#h%E1%BB%93i-quy-cox-v%E1%BB%9Bi-hi%E1%BB%87p-bi%E1%BA%BFn-ph%E1%BB%A5-thu%E1%BB%99c-v%C3%A0o-th%E1%BB%9Di-gian">Hồi quy Cox với hiệp biến phụ thuộc vào thời gian</a></li>
</ul>
</li>
<li><a class="nav-link" href="#t%C3%A0i-nguy%C3%AAn-h%E1%BB%8Dc-li%E1%BB%87u-10"><span class="header-section-number">27.7</span> Tài nguyên học liệu</a></li>
</ul>

      <div class="book-extra">
        <ul class="list-unstyled">
          
        </ul>
</div>
    </nav>
</div>

</div>
</div> <!-- .container -->

<footer class="bg-primary text-light mt-5"><div class="container"><div class="row">

  <div class="col-12 col-md-6 mt-3">
    <p>"<strong>Cẩm nang dịch tễ học với R</strong>" was written by the handbook team. It was last built on 2021-10-06.</p>
  </div>

  <div class="col-12 col-md-6 mt-3">
    <p>This book was built by the <a class="text-light" href="https://bookdown.org">bookdown</a> R package.</p>
  </div>

</div></div>
</footer><!-- dynamically load mathjax for compatibility with self-contained --><script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>
</html>
